# Backup credentials for Element PostgreSQL CNPG
# CNPG expects individual keys for S3 credentials
apiVersion: v1
kind: Secret
metadata:
  name: element-backup-credentials
  namespace: communication
type: Opaque
stringData:
  ACCESS_KEY_ID: "${CLOUDFLARE_R2_ACCESS_KEY_ID}"
  SECRET_ACCESS_KEY: "${CLOUDFLARE_R2_SECRET_ACESS_KEY}"
