apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release-ess.yaml
  - well-known-ingress.yaml
  - cnpg-postgresql.yaml
  - cnpg-backup-credentials.yaml
  - cnpg-postgresql-credentials.yaml
  - cnpg-scheduled-backup.yaml
