apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - immich/ks.yaml  # Temporarily disabled for clean reinstall
  - jellyfin/ks.yaml
  - audiobookshelf/ks.yaml
