apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - immich/ks.yaml # removed since vectore store migration broke database
  - jellyfin/ks.yaml
  - audiobookshelf/ks.yaml
  - owncast/ks.yaml
