apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rcon-webadmin/ks.yaml
  - steam-headless/ks.yaml
  - enshrouded/ks.yaml
  - minecraft-1/ks.yaml
  - hytale/ks.yaml
