apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coqui-tts
  namespace: flux-system
spec:
  interval: 15m
  path: ./clusters/main/kubernetes/my-apps/ai/coqui-tts
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

