apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared/ks.yaml
  - homepage/ks.yaml
  - kubernetes-dashboard/ks.yaml
  - librespeed/ks.yaml
  - sonarr/ks.yaml
  - immich/ks.yaml
