apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - n8n/ks.yaml
  - ollama/ks.yaml
  - searxng/ks.yaml
  - whisper/ks.yaml
  - coqui-tts/ks.yaml
  # - styletts2/ks.yaml
  - bark/ks.yaml
