apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ghost
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/my-apps/websites/ghost/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

