apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
  ## The Following are required by ClusterTool and CANNOT be removed
  # Ensure VIP is different from all master IPs (In DHCP Range)
  VIP: 192.168.20.200
  # Defines the MasterNode IP (In DHCP Range)
  MASTER1IP: 192.168.20.111
  # Defines the gateway for all nodes
  GATEWAY: 192.168.10.1
  # Defines the ip range metallb is allowed to use (Outside of Local DHCP range)
  METALLB_RANGE: 192.168.20.10-192.168.20.99
  # Sets the Kubernetes Dashboard IP. Has to be within METALLB_RANGE and not in use
  DASHBOARD_IP: 192.168.20.10
  # Sets the KubeApps IP. Has to be within METALLB_RANGE and not in use
  KUBEAPPS_IP: 192.168.20.11
  # Used to automatically generate a sshkey-pair for FluxCD
  # Has to start with ssh://
  GITHUB_REPOSITORY: ssh://git@github.com:itzteajay-glitch/truecharts.git
  # DO NOT ALTER
  PODNET: 172.16.0.0/16
  SVCNET: 172.17.0.0/16
  