apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wnd73kOhE/1LvkX76l1QMvMaHvyaXlA1NMd1gEOeWgIDUZwGE8LrxAz7q1yk5DtsyphUCuQ83pNiCU+1EIsQXfLs5/oyes4l40uBZI0W6GOTe83gDoB2K6TbZQX/KcqlJbV9/iv6w+28i6VoJYlImZYqmf8kb5gtXc5gs2RkQqriAb2k5XYAHO5f7R1jCmSeAbPeoXAr7XpN8Sw/ns6PdKPMQTaVzUL9OtVs7YyBDgWrHf+0+b/9sNvxRl+Xau/bNmhBVw8lH0W0QW0vONbkZ/VgPRSR/ir8UhV3swjm2RyhxRm0ih7opdJ1jehb2RsLvbvdCt8FJzppvssScuh4Tp03N53odrk5HkYr9LHwtRkx9eVk/3fhYhibD2XcL+jV,iv:o5OEV/4/30Qq4ntCdH30q6bhJzC9OWDndYsHo+Shzqo=,tag:HaBicR13VNGnpDju6HRgsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Yw6TwHe+SsDFKY9BZCDVJ+mT1ZbIwIqjAqkHFcHQsyDAnc0WxGMuqlgUWYQNFyqHKhWtDdGBliDg/STHYl844vjInklrhJUQCSiJw36ieFXm5nHwzgMTMgcxyus+Ewf5g4iIbr9Xk3HaKSG+K+Ft4OxHxP8pZaIts8v91+ChksrXg74alma/HtORidwrlq9LwKSK5HLGke/U/TmkWUFJ0KPsFFN2XFZb/ykoTqnKiMs6gKEt09+6L0/m21YWLpibP57qchGkyCm4WS/Eig==,iv:dDrEUCgcUt0Nx56H9jKZJ48t2Gz0bDaceIOIXJOXfTY=,tag:8MSdB4xywZvr8Y8EFA/V3Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:GetKgfDlphRFt1AzI8QNk1GWFXx9nAurSByzM+ft7XWYsG40GH5kV5kDXR1+b5K5S9H4bWviP9rDEIR/4bhLK9oT+8UsX7I2P0mVATPsiNWhA1PTLTr/YNdTG+XcaSFozdRWcOgvcsj/h5lHbFtnvOF6tfApvbE6RowQ74gvWRQj5n1Xr54PiJdvJKJpC4vIJSCKpdR+tYeXGQjoD0DxANHL8pSmE4/aHcYM,iv:ZToNlMsNeCHWabk7n228ZODCK8aFHHbkr3PshWtWDyc=,tag:PbQU55MuqRXEq3sKKW+pBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRczZMbFBPanZXZ21Wei9F
            c2FrSjMrbXN6Y09yMXFHU2pmbWNoMHVCVVVZCmZTU21uZkZkcnZwdjZMdVA2S2Qx
            ZDh1Sk5JRDM1VmhwU0RleGRTWGxkVFEKLS0tIHJ5d0ZxYXBubXRvL1IvM3VPZDIy
            NTVteENFQnRDWUlGSnBSREJYdC9hT0kKIRLEmW0/xkl+9kRUoWIPMzHcFgQ/z6vc
            VAL4YySm6Rr5fqDyx+Ez/Th+IzI2o/i+/hmetN9C8mPyQa7v0k8Yfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T19:49:03Z"
    mac: ENC[AES256_GCM,data:pZDDculRlCzWdE/eZBZR7LY+1evZk4BAOgS2BawkOXKE4RGZ57X9Q9UXrI4ZPL2/k5me1rHLxxscZOBlp0ZhPvCZ6poQGdW9Sf6SIgrvWqUeddgrLjFdGXwkLdQ+6WF9OwwTFOitcDij3+kWIz/rXJt854LJAjuz9K8b04HcN+o=,iv:HGOA1NNdoRUTUz3VNLZvFnA6JDFv/7U8N7xMzu6Yuc4=,tag:/HScbaagknWmUWMc+4KRkg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
