apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ppMT/Ob7JwxDK7lhCX2oiC9xx8gHfS4bwooe4rbL9sCp5T/kwWXJzMbY+XKt7t4mQMRJ+AxRxWPheoPkTihSnm8/l+x/lWErRw/a9eSyAsZxEs/eLNuQA14cRJluYeOY2gCBM3eYlrfSqQkC4lAPwpSCfakwE5JsbeeHHT+64Y19TX670aTYQFFBjJ/YPfsivizs0btEdybxwjPz4dT7MsPHUqXSJsl1+ILqkim3EfBA61rnHKTWeWTP5d195uzsKPXfPLocWjrsgWLEZW7totfe7haygm3WB6sAzASRN62h33xZEHQ5a0fZY4KquHpbDGwyFFaGIi5WvEqKP1awRFdMG0G5ku0FnCM8PbsLE3KcQ4myfMD1eAmN/zUNNJSW,iv:cPZ0J968pu2GBBFeMRpR9ZJ2bGUg1ylXroANPK6Jgps=,tag:OmKjfMV+fS+ickpIMKnxog==,type:str]
    identity.pub: ENC[AES256_GCM,data:zeUV3DBTa/WRTqCVuwH4+WJZMwzSaY/QaxuOnSUqWqWo1HyzvRhUN2d4HKdaT4+fWSWmlvVhvozoO6goMhnHiDI+nKwNd/iK9/0hW2muP+xfhDZt7i1NOCDF/svGhih3dEPtihmb6FyzF/UtesLdWjQWNsBbRJMvs+3ndX9u1FftAtSFmkboHvzatd/t9ESsphwI34b6xhAoQC9vQJn5K/erDvkcRVRP5VCxwOttPq2W1rjIl0rXtiFPnp3nG8gL/r+R/wM6tYSiBiIuaA==,iv:PIPvKuOLglwx1bDwIyZmdDKba3ecQfY23HBE0ysznU4=,tag:xaCXgHgPyf/V0s9Ha0szZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:QbiSEciFrXYng4XMRhMzD3+eznduuXAkReEAV3b3IFCYSL28HnVI0TREAV2EjE894demp0ORc6H23V6f8G2LPkbyOIducvcgmOAqgY6za0jvEbvrAuwo/hoq913htVZ7m2uWoN7up4aOA2ljjFyPTNSykLsY1qkMOGj1/bf+pFWTWBLczI9as3rOz2tfUaNfVGOtDotBbZcvDxgio+UlnDZj7WjMHw23RA9B,iv:4rS1IHfF1MOpo+Z22Dst0fwhj39FNOq3DbG3zQ8GxFA=,tag:kkhUdTFfCrDTTs+uwLnv4g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUmN5eFdmQUdUZkxVT2pO
            eGc3NUxnL2VMV1BiQ2IxMllMSTJ2aHQzZEFjCmhPTEpaekk0ellnbmlLQjJOUzF0
            aW16ZExsK2oxMDJmNklKdk9IVGk2WkkKLS0tIGZKU00zQ1FWU2prYTlkR21WTjR3
            YWRucWx3c3drbEtpKytOYndOMjd2cjgKpbbhlBC43iB4fJWNWsrdfYFaRbsIT/cW
            M2F935UMfw6b5B0WPnmUYv020938GcplW5p9ZAI+vwtr5AOAlmxCLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T16:04:36Z"
    mac: ENC[AES256_GCM,data:TfAOb3WMUtg1nWLVyOYTAmSQRkF8wpMk3VPsMtZuJSqywvg/LJTrxA7If4Wdo9zfav6pJJ/oiL9BlfQzH2CAlViruk46ifc5WOTDn/nbWjXjTGx+CyDiZByLF4FP5rdncYqTeS8ucRD13ln9evmXTMBqN/jp7IswtwA4pG9Agg4=,iv:WVjdvpDVPt/rZhYnn7MMQYjignuXNuFuuuqNWw2dHFw=,tag:j/FFo2v+ROjRCcQn8ditRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
