apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YsU5Aa34Ae1sih3To5zHq4xEa4VoNeMT+Z0nAq0AfZsl5WKMvukuQ2fi+V3cvIrCIpJaY0o6qQ63s9HS6I5/A8baJHHZF/d0Vjs6agkCbh8Cz0PcmvJ1axLBvhAHqJ1GPtBKHaXciSN3K+FeBCoXYMM3myf8yxT8a3EVMnu8o5bCa06Wu6dGfVJhU++65TQ/+NfCEoOmXHizxEM9PG+yFZN2/R2V2AOXb3GwVXerSLFnSC4JsAPxfT3nnd2ZFNZJK8Suu8nfxbwGICj36bJNnUzdy1Qvng+BsqgscGaIfq7GtkYDnF5QOiWsc5bwnH+J9ANChJwygVw8fCLDxNPRrXHT+sztMDo378bIJtyB0OEbwYJfUYpTcb7v7/TrCLxw,iv:drWJcwLGyAHP0/xWF0NxNifGzvfepBcE68hUUyQDgMI=,tag:K1V+M9RLukwPc5MJGqFViw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vRCgjCBQJ5/Udt+k9WF5a2ec2gQ3Bt+pDUMgzlJsZOze68cSzeZJvjpGH+nGAmhjbJ5/s6egU0L3Kt9vk3fYqPmgYnmsonz1M23yQ93YpSokwhthg2rx5qrrQ8xoc/DS62u6xILD8vfVAi4Eobq/4toOJpEtD5U1lKXHGgvf+5coiEtbrxTIcUHoRKQ1cBmkaFm/NVIyjekvI04z0Zh1Ze9TyfKlr57ZRsJGJW/NHZDXxfLnIdurmYrug6Zv3eOo2vf0fnQRcJNQoIe3XQ==,iv:Nuyh7bj99+pjzj/VnUKL/wPAd+dYdxn1DksduLgw36Y=,tag:AZAWhO0/3gi4EXcgiBbsWw==,type:str]
    known_hosts: ENC[AES256_GCM,data:JOSbP5M6op42JahyEFtr/rbErHMGmDyj0opbwKpOnHZlT4VOKwQQ+hIf710DkfEYo473Db51iVssT3epXax1OZ4osWdan+sDHgb1o6sJany5FrI4gMKUdKlXubXCqTuofgiYHXJGmCeJocLotBQZDEo9yO5Q94n24ePEAi02spY4IIbzYzVvz8qjMIO3xnOAFKZ/wvS9A74OAc4kyQtnZl0hPw6J1+HTHYfJ,iv:0A1b4K5tcBq07tQFbwoIehf7JGvRGm81MdslozZh2HU=,tag:gQvdoRy4HUUM5Q+BRXgU/w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVzczaVBsVFlSMzFDU2t5
            NHdKWjhKUjhtdDBDdEVSZUd5d3lVVm9VRjMwCkpEMnhQTlJFTHpPYkdoaCs0KzNH
            YXJSVjRETi9FNmVXT1c2cndMbmtpUlUKLS0tIFlWVWkvKzBzaUZ4eFlTeDVqVHBU
            NVZtZUdaUnBIazVYWlRVakl0TkdDUE0KgtKXyOankTUDP+wHDv+IDiuZ9WWIptJ1
            Z5bdx4goiFkOUeu7NS4/WUELJ33cmYuNyhaHksfNLh04VxUX5NmTFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T21:37:19Z"
    mac: ENC[AES256_GCM,data:FE6U1S/Kwpm1x3W7cIlcTxCgkYFtKrU/EN/DwvmKyKZ/44pMS4OlhtwyJ/EGqXCXopuNZsrZ4YDzuRhOsido/9Yn0RFiBTmLo+BqmO+xTYtEIy52JrY9cgVni1MCLnEnyO7Ufnf1Ur1HtV0UF0p1BhGjQPVbmPIqQ7T2eEVYSmY=,iv:yOp25EKI1380ns/+dPUW6MlhkCDmGBLMJr03xA6oX6M=,tag:901md7jtHSrlroK0gW1oHw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
