apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:15A3zRxj9xYBR7TkiYSQKAlyCEBNVBc9tOZDVaLP+yC/UI7CbvE2u5y/GaP0I7fa8JILZIeghDGj6aqRW7EbySpGP5P0aWn1PtcgvgfX7h1Dl7sb/BWXm4T5jU+JbHMQy78RHJLLXVe3//42zMoVCXHwTaLWIf2x6FDC27fP5Bq7SxQ2WcsWC9NEobI5A4cbToR27ZLhmcYodQxxYkeIWHtsvLlipf619jqExTexwiJOHknpiEn13ARtvzL7pYpA6SOYhTCNWsdiqDVrwTLGhhClUO+hollmLfG7XRaWU0E1lRYA/QdcwWC7PbRHau38SWHbMktfLE/tuTv9P+hJgagkHOPaYgygN0FlfsuloorPIX6/qSlPEaypaVCTDhtl,iv:a6kgop+JlcymfBoJqwf9Zr4kXr//qZMNOJs7woCAHTY=,tag:k320otLuFo64M1N7nkjpAQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:rYQGlUYhOE3tk2qYdWdz9k7YZe69NG8JYAvn42V0EP3Rn+Q83u17LHBlV/Wz6S9TcTLR9LfmpV5Ca9fG0n+tmJ8IL35WnZfGMGXJZfYJrotDHdm7WWWoEOt2Kytz+dukuDu4gXq5FCU9QBjleDAAx2nz1IgfMo7QvSQxZtpvjA618LgWbkagNqBtjR+2eaI5l6UXBoz36qzAIhTpQIjKrnEJL3EthTw2kZbMQnmFhPTbAcPYeJkJixChq+oopi81D2yzbqo3Vhl9pGuoeQ==,iv:DNSdLxh32hvvIvqb58KmwCNQDI+4ALhdgZqyMW31zS8=,tag:1/yv+jWJ2QSmCQcfSQjVrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:khCc6cIgfv9rAD/TbPkNPsS7hsBhIWAl88b8fsedYkZJlEINa4Su/aYEw1gLYppW1HlWT+ctW4TOfqyvuKLFAXv/QGU3EPe9MrSn5Ho4fk7tZ1abUF+pYA7DQf7cL7Ofk5wV81vOgZ+EJrPlVheRt+TDsQSZPiV1q+kLugZrw5YI3dhhS31peERx7f85J0JcvamsprfdYbpEbCwWO5yAk1KsZNZ62cW3RHrk,iv:2znZvLVJ9z9RX0BOmu48yIjvot5+Rmpjkoboq/06mYs=,tag:4L8mgvG0gFBcDhlJAl74SA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c0NQaCtFNFU4VjdPZDd6
            eUZxVGIzUWFCTnJJdEkxTUx1aUptZHdMckNNCkZRZUVuM2s5U3hqaTJCRHBIYzRR
            cjAwRVh3ZytyMDkrcm16T0NnRi9DSWcKLS0tIEkrOHhCYnJZazdXRHBLWnhoY25B
            V2pkMTBTWW5XbFV5NmpvMmlMOG1LYTAKLCjaXv7/8S0mRhxdbyXatgvSj/V8D6Ku
            WmVOz7I3w5K+vVtXyphWYbceNt+Ufu0PrQURG6ZwbqWDDyX/roPVkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T20:07:36Z"
    mac: ENC[AES256_GCM,data:c9JXWch+rNh423kr/JDabKz7yHqwl1GDfB7twI9kvFvF30xHDSX3mrtSKf4tSc3Uqfx+st+gDOe1R83X0jV/QZklTXt7hTe4q2iIQJtEMPGldOyl+C3ZdO4Z3gMvZ6ye0XZ0EuIwdZMxZQcoWDHu/IZQEEnIaltg8t8X/zXnsuI=,iv:8+NkGypHsbZNlo+p59HpkvmP7yKsch7tva9H8DYqHuc=,tag:ACdm7jPHZxfsPUYWXRFWRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
