apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ePYZlNfNgAbeHWQnPcCw8Oesl9Hhu9Jq2XI0VKbJqoETYW5qadblo+V27lufX668XBPrpgBFFNSd8zh/R5ucJiFVrd+rCAgETpr2CKlRJMu0JkinZTqOldl6XxXbG4RMJJv+ZPGCMJGjNRt/4rD3SMOweza5oTuRVe5vUD8WWNqHlJXSEGkwB5l2nnf5dhzc2m/ghgGc1h8gMwSyFcVKNm7CISnWHgx1E2CGvVnylmmowQvYrMVs6yI6fESvzbIk8D8G6n3w8f9C0wZuE9zctPTZcD6gGIk+i/ufOSOMgGNGMGBqYXbuEUV0+oCzP1CJOBUkipaQW7dJ1IYMzRD88GCsFmYWvYFeC55RG96D2p5mUFT9mzADHVM1Z531CML/,iv:TpNgTJZRpjxq0rzpG/m+MtlVmBdIyskt+uLQZlf6nok=,tag:D8LbiiqrmvTOWq8LP+fanQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:eiD9hHMYsWbqXMwOblV2wpg3lpClz8wS4YXOZ1325uSr/JQ/5b26iEFNNA6gKWfU0L+WT83ZSj/Djy5dvRJehYlaixCnrA5Vx5eOYbe7J13Czv11dDSZFpuF8i3Yu0y4OCzoNuQWJMim35IrzV/re8GscmYY8B+GHM2epfjdXWQewVm2tcJsQ7beuGEfI9Kd2BTPhCU5D5ANqkyK+g0Q1Yhec5z/+8oWkgdyMGln3ZtWJ+/H4UlDhHY6M8iTNDwl3aTqJAtxEVkAu89WsQ==,iv:1sif8yWhbKiq7GDeaUVARUKZP6dMUPq9NXJIlpP3jic=,tag:2zjePkHlVE2MnAFBb12sMA==,type:str]
    known_hosts: ENC[AES256_GCM,data:eKkZC1qME9EdCy9mA0sCxsTskTyjD7RC603CKOB8k7+p/Z58NAeGd551pMXFjHoolsA0Hc+LNNfmisVQjBEatY5dTEsbqj59W6WlJQy500aUoVX2+IxXr4etnTWCyvQCFVINCyJoac9SLlgL6NRgEEbv8+HJkO17HnyLhDqTDO/ehGRFYV3eygcS5UFw0Trjo09UUtotm9UwuoNoQw0Chf2EBFwzPssS81Xn,iv:XKKS9wkprRhzkgoVLyqIKRtdEWDkmeGDdHF/fgGbAao=,tag:vSP4vd1OHc7s1aMRDXgCUA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVGZKbDFVL3NNYUNRcFVW
            ak13bElpZXNHTnBjS1J4ZVhnVllJb3F3SWp3CmVrSEdDZnJHNkFscTE5SWdaMnBw
            dFhRRU9mdkhNMjBkdWdJb0hpazN2aGsKLS0tIHUrU0x5SmY0TWdSWEdOTkRsWkpV
            S2RvK3c1SHAyN0NjcERrVXgzSzY2c1UK9E+2JfsTiGwHxIL9ygZB1dns4bbmu2u2
            LPct2DQdw+x5kiwCnJie89EDmxFZWxQE3XnRLajDZ8F9BfqPMBL5QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T04:34:51Z"
    mac: ENC[AES256_GCM,data:iVYQw1GeZ+powrtbE9rVGS+8F/64RWIMWjJ5nWPQoX3+XVU63qOo17qkGA8jg27+FexqkY38hEmw2ytmt4IGytC2NhdYUCsl0e+BuY2+zUx9UWdc2+lbvHxaGktUwZmFA0ZXr85QmdAvELgp3y8soFwQLhbe6sszjso0Kh8bUgE=,iv:eZqbw4Ke20IziHufPV7pcslJJAWaWbm/sH2kxOIuPK0=,tag:/3Gz3p1Hp8TlbUGNwiLNEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
