apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:R7wPOqhjgg1TM5FL3PPoPA6S2b1TaP4Myw1PX5asJR+eSZPdVs3nJodgtRx0Z1al38BXmGfCGdSdmJS6QX2hLpNr+PwF+GGJb/XTR60e6jXujvPLDhqiAERBgHE/wGiycVwYlTzddlnD1U/DrUDnMMF10DLsqF2SCj6Kt3slyQ1iBe0s3ZvbeAdMfk9tA/aFNt3Kpxn/QzKV3VJld4t9LLcqzJbsF5c3SIjnzbjmXmYnfkqqG7gIDQ9FqPLz1WggSzMQTVsZ/RT1XprWkxz7tRLmlkSwt4Ts6vQMWo5Qq+Q7R0a+HAPKZU6ESwtFK2NVXJK7FnIBASaJ3bET5viRBb2qc8iET22+lxDNYsnDLM15lkXRoFMLT2SSv8juYHVQ,iv:3Q87RxXpL9BnozP9u9JovCcOux++XkkC7wZs+jWRKdI=,tag:3+f4N0gRznrKBHIdg0meMQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:S+SO5MAhS2lAT6hF3SoKMjJ5P6Hgkb5LLW61zH8Ys2izz4cB6OS6tgw9f7rA41zGd7fTeXqDqLl4II1x3ZJiOlTW26UOTBSrp/Ve+XQyInz6xUSpUD2z8evElyOlXgNjjbpLJY6LND+wQMb3xj5gLq9Kn1WyKHKdFzn7R8lSBkYw+a9YYF7De/EBPzJWynXE5ZeyZBbCJStq+0OFhjm4d1OQYdo+cWeEg+FU3pt6a/W2G3lvQPcHCcPzb+nv3CKhFg/52ZDicI5NMzPKeg==,iv:gupF6tYBJ9j4Dhz57c+h0QLVek3XybMUdOTOqiwXktM=,tag:/Bq5i3sIDtdVqjoudLBP9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:rB1nKgTSdK+K7qpldS+uR4D/4WdoTmBn/XSg40ue1M1f4aJTI8J5TidB5SPUjPASgHJX8lNz3VVWuD9rekHwqvV1+1ltg1tbmOz+VLl/26tqqbA83w5DPzeniO8mTPu9IHZSzyqBJlWvUndFyHZACjGd5q//1xpl3L1onJm9tHkGNdv4Cxz/uvsew68BZnkK4v4Inp0GQiCQJBaYa2pnmy6MPK6ds6ZGrI4/,iv:rulDNKu+8N8UvU/DfBevO/c8J5CW83UakyUSY8pYEjE=,tag:1Xr6nvjMiWvLJrU3eVQWuw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUTI4aHJmSFVSVS9XdDFk
            bjU4MU9DVzRFRHBrY1FkMjVEK09jMHJFYmh3CmZjTGxlTEJjNmU1UzI2R1ZzUDFJ
            OWFYR0FSSWk5WXNpU0ZIeStIdGQyYTQKLS0tIFE5N1BCRDZ1RWFwTGV0dVY5SGVr
            SzVBSDRFVEdYbWs4dDF3d2lrREJ3SFEKte5vtaKqZGdTrwix72pGaHQj7wb+AHKE
            naTloGjq7ulgbeLx27msTr+9NZ2BjuI+04fKjX1iWvK3WqWS0Kwc+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T06:00:51Z"
    mac: ENC[AES256_GCM,data:4tSmP9/wH8FaQ66AAhnf3JczblwS63wpPpSwBcmrxBhZQFBPCHJJ1FN/XkmUy1X+iuJ4sx8EtC9EaaTxAfRjVi8ZYbITh6NwfAY+0kxos9oHGgnn9URkjktk8SnDfaaAF2mzTYzuBF1b92PAuVVZP+Q4yRde6j6Vww8J78ron+k=,iv:qPmTJMUaxE9548Ys8JlyJ6e69WnC48gLz2/D5BexOZU=,tag:MESBzJmm93czLeef07eVuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
