apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dMcu29bC/TsvLjaaFqAidOw/fYfmwUs3WgAAB3e4DoBy8xFCihWcfig93/pmodrN6hHdunFPDWwN+cBOCI6af8scbF+Ue128LOZwcpdeWwaUy6Ma/I+fG/E97f7A+eITyNManb4mCWBrLNhKy5MCHO5RCeq+7q1JaHJjvce22/O+mDHF2414ym1vYvPEK9gDHmFJLYDxaSvvSeXwJ2XRC7WhNySSBS3pXXiFq6FOsQxMA+j5DyBN0z9BIMlyShaRbMmiX8lBYWBj+CKwj1YdVHkvXzMB/nmHNaYOCkes2cy/5bO286r36chFsmQfQtQ1fmKy/m8pfSJnxpAj2WfWt17696fZvhlTUdc3Pwq5bll3utkh/8H4lZl1mKlWa9e+,iv:GL5Hrdk7ZBmp3a5RjOH3e40pMb1dbT+XWVXY8jaanJU=,tag:ILkDbk+6lAtCmo6+W3M3ug==,type:str]
    identity.pub: ENC[AES256_GCM,data:Af/gjnTAra3NgB8CcMDLr5RNlk60gjq48A/ESCI0xfvTh2NgHjlz65jt9ypKshOJ9GVA09kPPBb+dRW8VttKodT5RipHCaTVcLkZ4W+jIoYX0dcWnnLeTTplnQTZLyJL1bTSGD4ADQxFlJZV7yi1nwrGcPpsNtJbrw4Tni/42l+oHIwSCkf6vzp/Urqb+BGa9Gyi4OfP8IJIctBbK93t8A3eY+TRYYjz0dmT2xzAEAF3X8FE1f5V08DSL0xiD1ph0bCXwvSfpKhS/JK7TQ==,iv:d6bzQZekyxqcRvjwqyPZJLixesAHI0OodOCebOdh4kI=,tag:zfyCORrw3lcgLHSTDSnUOA==,type:str]
    known_hosts: ENC[AES256_GCM,data:D8dnvnD1RUbaq45axMntfOMHFvDnAt2XQ72Xm+zHdCzxUi7M6eDFInNPU3LxWiIcEV5PuuSA8BclLrR5dszTLEa9GrHoG3hfWgjvcvmZArffbzQxGfaPdUJ0zq2vw7cfriNzRftuusB8mcwhb40/LZ6aC8JnnNORxJVhp5jBH3pFoPkPzJy8dyl5mqvWNHX1Ps8cZ6hSACuly3KdIoRZZxbd47V1dmaCj/Ne,iv:D4zgsxKIAmLp7pRwy2vDZpab7MJk2aqV+JTZSC48xOc=,tag:XRPLo3kHKjAAFvA+/eOvOQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MTlKNmhONXVuYUNocksx
            dVhTTHhVUjJjbDBWK3YvWmprN1JFYkVjTFVnCkR4dm00QXRmUzU4SlRVRW9FMzRX
            VjNSZFBBa2J5alVDMEVhcHBDY1AyencKLS0tIFU0RTdOQk9ZcXp2cUVoZ2FFZEdZ
            ZmxGZmhyRzYzdFlweGNhU2k5d0lNbkEKSXsi2Fg/BioQpq8ueV0EBY1a3JM14L+f
            nz2FBWCKj2TviTJqQRlLjcKea2vampzK+oJLwAAx2azX0cl7CNeKTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T17:02:38Z"
    mac: ENC[AES256_GCM,data:12XmRRAJ3b63gROlxVHiWB+y9ZrGzK2mkU4VME6X9ObFuDPQusJdcYeGXArwiLXHoQZRsZ48l9939eiNyZlLC6KprdrMIDw0qv/k7OJ76YbVBV3N1NhLdA/keh1xZChlBgORZJIK/4yLI4vyTfqAI6A5UN9l7XGuXBdFv2aWddI=,iv:m33IkWkVUs1CRFJ9m5tuQXL++P9173137+NAU8+DKdQ=,tag:DLLzSU8ObAWiLQ/uZW9JrA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
