apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FZLr6cYJjqL4HVBiANSKrn4GfGdpur+OxVB6LNpiGzGEReqpTOizBZVKFupdt2KA7iP+2bWi2D1XkNCuZp8pxblbMg23xlpBBxF/RyR06eXKXbdnU5zxahNSHCoLwlb4sgZDPNw16SJC4WxQIaYygBPBDaz7I2LnKi6qYNKZ/eCvAfwnGA5e/ua1/xGdynGYtuaLPYML0Oub/AskoEMu+vEHJSeV/qGt2bnX7KgxAQBd55agCjEbjCmyKCPfQy6dsgZ3k/++9l8ycBfryfszpkLI1irHgdnTXE0VMjzieDVJ+CWHcfSGnk2aN8529iTDBtDuqWvuR4J3ep0CK5U/9j3WL1knZpr/vVQm55DGXqlL4XXFftOFjPIZ83WZo/ml,iv:kEVUp6l55SWFn12H53Byq+Q5YsJfpLKdRu1CqtPpatM=,tag:9W7ILd1/t4djkxKuKeFqEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:zwzZ8jfiC9HicnGrtMyTaIj4SRajZ51pSv+5ja1e+1lkWewoL+3/G90ZEZGLmld8QZu1bitDg8t6JnaG71vLDMSDYwE3IpPygdY2YPW/cjNEvBN3VGOgvgqPrqBIOVNLLd5NWoKvcVBL9UvJxcSKCsztyQJlf67R4+hPJkh/8cxOpZ4YKse+qs1x/7EnRsRUoW8bRcwiN0APV/mtCj6fAlfqDHxWNMjN2J4GrJ1uYOYqgkInzvsZaH6KEpv/DsvVgl6V0u8GUrJRWA5VSQ==,iv:h9SF5E3aY+M5hnr5BeCpyXwa/kv8fidm3vfRFrHjp5w=,tag:MxxwVZo7R0PkEghYlEsB/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:LWF1jJwxST/MgZqpV46aamo/l3nyMM/4hLWdLQtvyttzqsZEyeiKp2aIC2J8NL1f2YHAEbVwufinEexE8eIcOE96Tsz5tLXULPZKkAP55YxCDYIMmtYJNMHiXE3t1unGuoNBA1N9JVSSzcwnIoS9mCjerKzEJ/hY8k+Znbu/YCp1F0pwXpaYXL4V6ceaqXx8tLfZuOGi+kZbvq4Oap8ytHeWybdWmgpOW9ny,iv:M3oYhUYyQOICz811x6/Ay7Co4ro/yCzZY016z8vrNqc=,tag:dAa6IAK+JPbYA4XDFl62aQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWUVvdkVGdW80QWxjTFJz
            S0k0S2xoYUZEaFd6ZHBFVmNVM2FLUEtCalNVCnR6bUt3b09HdEFqS25MVWtRS2JL
            LzRwZ1Q4SEE5dFBmNUpSdVFQZDlTdzQKLS0tIGUrdm1WUHYyNEp4QXk0M1pkVzBw
            WU85ODZTRWFsY3ZUcEVHYkloY05Lc2MKEx5o1MPh/tQe/m9D9v1IkaXvp/kZh30C
            j39tViXt5dzavSuc81Ulhj30qTWKy+IxV0nYRqIj0xb0Sh6b4X1AFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T20:05:48Z"
    mac: ENC[AES256_GCM,data:tzvcRCTqADli9yMmIfECXsejAvghd4nCOlFO9OX+3oLN307DHq/vGHL0HDvq9X6twGamGyhpdU0jmYP9FvwgWnhcvx3DaLlFKXB3ew0Azvma+iDQ55NscBcPOEv5quNpv2R+0NpEavbVmXrfOlC7m0Zbo1uye3bpdE5BqPNpalI=,iv:dSuX2cJQlkRT/3AdzEOBjjf9KZXbKC8Ky0TJNK6iia0=,tag:GDn1s07AwMN1hUR/+rJ2TQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
