apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ezYnRkna8tXmq9wVMQUAViaqF/M6TYxoa6eEM9LfVlM+isOkIFi281CG0+epuxAgQKUEhiLaqb5z+5Tnpm0kOhWXa6RGc1aOx2ftMCvK92TIhCbWNKpVNPA8MpGQry7DkzC9Ouzu1kJTNAAAg/R5GiW8d3h0nku1xpZMCQmlqY6j9Yg6cR0LgDYYdWzv5whalbte5OaThMHTiK+r+ANpJ++8bdQz324IPSifdkutVrfU3AdWLEAE36Jkk+tEraVIg7/ySB94gQiDFexgAflhL6NpdYO2kJXX/yusFJqmRuRPhElxs+pCn+A12oIzVLtpSw6azwpLRQ0cn9c0uDEi6ufORFXjZfsfkcGhbjBatiNpQzU3WmCgwSh99rkvFb0l,iv:unzHYvSuX1V6UPv2HIGCzOU28MSjtagTqTZxlM8sQfs=,tag:24zgcLjOqv2/KcUIN+WfoQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5rmaW0ODcJdZu3L9O+8NtHywLutfOPfodDoznqPbaIirLhPg0So/pehKJIfb/6UIZcDjTyCPcgMXaeu5S4HVBdXMhQMUHyuay4bUPd0yNyHqIt5gawpAqAb59geruKwv75MWbXxViHu9o9wr9MZQ+Hqov8d3INO3pyfdGh0TaWZPbrwbMFxwFBvhU91QNdQxoZPbCoL68Da0FG8hVh1V3ug5f7Y/HR/rNSYhnKdh9Y7Cfdoj5PDkPw3lo0KZVmKitk5Nbs/p+1VhEBQUTw==,iv:3tc9EDb4QfrE9o6joYsuk5+ZL1DomH8bRRy9BNlaiVY=,tag:smwFXSKsQzbAX56NwlKKug==,type:str]
    known_hosts: ENC[AES256_GCM,data:+YSbnJ2fzyzIhXnWyd/Ib0fnYN/2C/AsfIinw36gw0KJO2C9UxwBWP0cNab3wys/YodVkbpjSNRFeWdDyD+oXO97ORvIw3oYtmtXgFHlq/QRPmoMXeVRJKW0f/fUvNN/fp5MnuWmFcDZbSUZxm783YQgyUVjDABc4twWmhvjTktnIEbXYLi5y0rzdGgKizkt0o2TVrfx0AFeky6qwglzzJUTBEDh1m0la0RQ,iv:ftSqDaI1kzgmJ2JYZ2DsqHmLKWLtk8SuKTVh5Yrx4UU=,tag:HJe6xu+YuR+fFZdlirPjHA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR3VkZ01Sai8yR1k3ZWRx
            TThXc2RLN3lqeDAyQk1uUGcyOTA4QWFGdEg4CnhRakdNR2dseC83QzFFYktiODd1
            TWpacjdLNFc5UFhVM2lzMUtqandrbmcKLS0tIFlUYUEzSzBEay9zQnlsTmJCdld5
            Y2NQRGlvaUs4bUJLd2ZPMndqS3dvSm8K6sc2AJFZ9o2kU5AjEAclCPxG/9IIim7i
            POrmu7NHMmyJ9eaX4SmHgkiAJiv2WLKp/E/FglFxSk+RGeKOEdgNOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T18:26:07Z"
    mac: ENC[AES256_GCM,data:bl4xvDi7S4RPufQY0PHWAagC0pKZFvTSO8v2Tb1jLKaPRuu4bEjgwU5TK7r95TRjwhahDl748rdbIsGiL1gT9yk3H7eeIbkqV3YAzPgeLiWcHpbIBHcQg+fj40akQ6Ok/s2HgDM1wpmXhmAkxrVZZv02njbDluzD1f7V/O5sZ0Q=,iv:M3F/9Ke8bkM01AvixhiqZfz+74/Pt/a404JHy0Q2Ndg=,tag:wawd/PcS0cKc0P/DbUdG+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
