apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KlH+vUKaoNUx4OSGqAnxxcc2B6QAuptR+VvoioWXmVz0e4k29JFtRRFbyXAaH+T+0BdYyo53gjp42MEUc1mN3HKRmK+V4EZs1MXacliZOy8Y2Fs68ZAQcmPmzQ9txYwXyQSRaJoxOTzu9CJEHXnsLNazM1IyQpCUCZYjI+ntvzEKuMhJlzOoGp5bAn9LQ+TzWJr1WWejjh0cfhFEmHi9wYeI0SMt63f0knE8R5+vo91CDIKXklxsgCFYJiQA88iDoRT9j8C7oI/ssGUUdrjUxbh5JDRqQ1bo0MG925ctZu6f4rHhgvnfJl6ZLoJKK/2j4QzOaqQ1WM+PtyoKbNoqmIoCsDgj2U7/EjjSyNy4Spm0POTUpsCje0wgKPJjDDws,iv:i1Uw6GquIantsJ7xbKx9nGM0kJ+O0kNlqCU+KKaiACA=,tag:7kYXB3jk6UIDzIEnDgCfMg==,type:str]
    identity.pub: ENC[AES256_GCM,data:59HVsEcvjMDCylnnn7WJvggBxakbOe0f8MgGi/E40dcltFAFGlBMHVUug9rZdjhRkGMnD4GaCnYi9S1PY1CijONvtWUq4B8Gi9sF/PF7sMl1zFpUBWozZu108aGnI1FdiV9TFIH+TxerCCb3gZuH6bqwcTaExcs4iBnOUX4+oi9FVS3XJqZQTL1gdwxt3eBjE5VJYtlWJrrqpUYePOcE+S5o3Sp7U9FrvG0YJEkXLVrAZdTQOT1Ht5YQT9W6TuP4oFzj8sOh/W07W8934Q==,iv:asD6il3oZ4yp0G74gc3TgeGJ/1K68+Qt9SzisTkGUYY=,tag:+THlfewJ/j8atx6zmGv1cQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:9WdNJRmgPzHOQXBVurwIdIpGG9H8h2YmkUjRW8OHII8qfWP7BdXpyJ+8pHS5BCUji3RAL9ZN87+AEIH1lLzi8fZ8r4iyG081vG1C6e94GF0iIRfeu07DM1RaILi3TRB5MGsemk0q65q8HNE/5pfXHAPslzOu/LE14a5DXQfp7D9UtN3uP7MnH4XIqpdgztUMoWI7iV0E8KhJ43EO0djBcYNxUvpQBb+OlxY1,iv:Ep6MtfZwLrHgZiHtH/eYRf3CSdkOza8X+1j6N0GgvEQ=,tag:2Cu7dyp9tSx3mBUF8S2GFw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTjdKZ3VTbjVUSms2WS8z
            dDlrVTJDYzV0SDF5L2I5ZnpRWXREMEIreXhJCnN1dXczdXVGT1cwbG44d1dJbFdm
            aFZ0S2IydE0vcEhya1dJc1c0ZUhjaGMKLS0tIE8rcWdIZFYxRVkyODFXckg5dUhU
            TEJxVnFNN1c4Mi9XbCtvVkxjNnZncmMK01BXMJNS/QlV2SE7ZFIqPwWRLEqs1OBM
            1LHPg8meimM3gezQaHf7mvIQZrHKz06OmDXaTJv6t/Y6LiZWUXwk1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T02:19:02Z"
    mac: ENC[AES256_GCM,data:aP/OVYG+XmsASm8spPXwu6G8KQSs9Mn68PMpUU6dkqsr+UNdGNiZs1jtFyKzqUt7vqhye/7wWN3HYrBIxq0qDL+WOyvbg1PKRj+ir3JtmdF9LcN5BlSLoV/6poQBIh15So8OLDkBo92fu0E2sieK0OvRSJSwrElevlfIHPMnNAk=,iv:gIHRwhCoPy4f4TSF4agxIvR72yWGGBf96+XRAzNzCCY=,tag:dZfN0g07czpjuIEpHUcMDg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
