apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pk/464cXhye298pnAeHp48OTdWSbdnOiKRDGYpJ7sFQzYQuiqsSMzdEJQ0WCwhJU7NLalbKXDPAmvfotpVlPpgD/D8CdayuWsGetuiH2t+JJMxD3x0UFprjjoU4vwGoO33wGxtLaXvBmJXKtf4o+f9fgUaMi5GSAEO/JxpQr6tW9BLBVi6TnEc5hvQphVCrP/JHzOSWGMRm2+UKItx5IbYlIFLmpHvZS+6Z1qrOUx2gA3+MH6JCD0eX29X/IvReXqUv8Pxql9Jjb/Znp9MxzcmaxgH5ZKqtu1zKH/w0sK/VldxFKOVq13CNHBjGOJgGHlW4a2m9AyBvw1cw24F2tO3I3onumtmMXY2MrQ0YaNoLpX72jH1xgHQcXiyGNGPeA,iv:OeSRemR3K+n8dQcsnObBLNY7AszvTnaaL5rtSu51r0w=,tag:fev045QfsRKSMKgfxuqC8Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:F00qr6RNgnlxg9jqh6dtA0qOYYQVfMcJERVAf3Hy5EfrdlWyJgizzKB8Kg3GezjYfXjyle6Iwiw4MDp3qXBrKkZK+5Cbhr4u312eA8/hveJ0YHrFpQJOGESYbVHltdrGcqyINOZFzeo3Gc/6wrF9/CPmaeLuwwwbPQEVvXUlEGgnN9mHK7oUurNraoRkeVpuw3hcjRwRxvvzL9u5F/4Yb+RdAGyekAMKzDoXQoOu1mWRimAd/it5i07/P7OLkMhiX51OAPKfoRLy6ScTEg==,iv:WOV4NBukO7UV5AyOE7DrW+IimCYEbOftiZLp44dBULc=,tag:SJ1Ff3RttWGnFDg8M7NZSg==,type:str]
    known_hosts: ENC[AES256_GCM,data:DxzJ0ZOhQP4ILapqHh+w8ppdvYMKYPqzshbMGCo3olf7b8o07AIukzRID1ZDwrA+2x9ScT6uowG5SQ8KdlAqOD4vS0JiNLMqA0SARew+eb3iOwdzUumvhUO6utllvroZP2X47ZwmtCa/ceFa+4GeHt5Qnhe+g8q/vzrFNHkiY9G1OcFp71V5/r/GEBmfzcEF+vNqd8qD9edeBBC2CfFNknAVbl5DegNY3C1A,iv:MOfVh3f098ZX3kTyTSI5UGt9g20bhNYisZEynI2xuEI=,tag:e1nlII72dfWnibG3x/VOwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxR1NSZzg4Y2llNVJJZ05x
            aEpkRk1ZdmszZVVPUUw1NkN2cTRJZjJ5bldBClVXbkIyZ1BEdHpQWXBJdHkrdjV3
            eUdwaE9PVXdRUzZGM2JwLzVzQUxEMzQKLS0tIHdOTUFVcjRCd2wwSTQ2QmJKSWcv
            WmE0SnVFQm9IcDRibUcvQ1VtaFFGM28KuuYDVeGxBCZfMaaFuUH8l0WJMYbA7Vrk
            I8Rk+xO5LIVPrp+EQymgSj8Mpa0v89C2NgtDDCOn2fmxXTP/vlNfGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T05:40:29Z"
    mac: ENC[AES256_GCM,data:xtzkk4UAgDa9YD2KuY27ZsSKIL58Y15Y8UpOGX2cX9eKc5LmPzxEwZbJQmudqiP4cnEt109IsyJmkVX93bCteN4LjFTh6yYj88gKkNe24lylBJ0D3aJ3VAaSbFONc3NGdztsWClobFl+SIkRhmqtXIpuoTc0bXtorM+YSL0qfoQ=,iv:AvoT90KB5HmHWDunyTYFycEblzaSe9D0XCMn76w2iJ8=,tag:J4CNEFQwICZUGPoNPRG+Dg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
