apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ku9tY0bToKBmhMqEZbtAqE1guDzSqgBCR5+YJQDqko9gMnHay9YuT87ieweSzgJEiSzpS5Cjhido4uL1V2gt4vSRM693H8FqKHaNhZ8DfC7KZG5lRloN5RCX5HBix/pdiFgOGeBlmOQGJ0PCfVmA9J8dPb3dYteCV4vCGpFmOfzaaj3VfBu+Sa0rZb+uMqkNq9HtpNXEVYt1Nak0J7jA9qLEBSjrv6iMPgXuc4DGJsEZn5FMN9BBY8fJV8D6oHuoPFR2W/c0TSFuIofzpACY+W1m7qf/NMMvTiqmVe3/ogDeL4OS19JU3KUIOSnheozku9jufS32usBraoU0eLsmLGEuSYUegMnTzdMR6oMx328DVE2zuOgulJtg7B38v6AO,iv:Bp1n6JRrxY/sxhmIuA2gmZ9xJgZAekwGW/i+pt4DKQI=,tag:VHV3UXBMpGn8yhlebPt1Ag==,type:str]
    identity.pub: ENC[AES256_GCM,data:qp+vaGHBR4f96gePWbfACIS7IYGoi8SM4hqNUXasPLhJnQh+FYrPxKDbFfoHIbcRjfzukHENY9YWnqGg3NCQg0gPvs9JhXjzb7aI7a5NdOjSuFRTa+dobkq99B0wClrhkaMtjrAaEvV7oiGMFSqBmvc0Dd6Q9FIWBWHcjqz6McJ99/99NnN9DvdUOChUYzKM2aktVnE3C1Yur2H0PcRsk/Fn3mufdEaQ/7h3obv2rl7orYjB0RuGlFjqZQTCu/13gcm8oDflBCOxc3EzxQ==,iv:LVIeghF5acJn9eSmUDcJo/LwgxNDUaKnjvrHaesOlJ8=,tag:ZjBi1xM2+oC2O1EOWa2c+A==,type:str]
    known_hosts: ENC[AES256_GCM,data:W+phpgMACm75/g6IJ6jKv8xq5BBk/b+Cb8Qx3SIKYF8gDaMJz50uaCK0kLZYJ2n4W5wNBzVVtBlDheFGAh7Agh5nBiBDSzAaaT13c+vPughNMOh/RYrs6AtlE8/eergftb7ECSsTyk+y1qXTqfBNq0pPKbtM1Z6MAyf4eSAoobgdv+VOK13aKVmlP8fKvT39AlPxJMe/hOdwoF3laOaG0L6z0QWCDcosTR8T,iv:mITU1IyBYAqqtS306gzBZKaIKC8+nk2bnFjk23fwlmQ=,tag:E6/mwKxnxbVpGR1YBVfR/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNjdyOUlmYmVXVndRaWhw
            QzdCbUZDQVNvQWVyS2E2UjdZclJ3cTRWUXdzClRKNFdxMjVoK1FBaVFkc3BSUEZB
            Rjh1Qm4wR1ZMYXQ3VjdKR3RMWkJDSG8KLS0tIG5ibXEzeG9jQ1FTbXMrdElEdFlp
            VzhKeGxRNnF2OWI2VjZ2ZUVuMU9rNlkK73zD3x8y6RhJCgjJJHLN7SKy6X3ve07R
            i4jFOdXdBDQqSMIr6J4tygW9e9dOfLWDTaHQZduEYuwUBv2OgKVCFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T23:02:17Z"
    mac: ENC[AES256_GCM,data:XcCe+xYUR7mMo+sUup+3wtjHX+yX14BdEGlDqTS7MjZQVONALst7ep/yb3pAKoQ8Nq+F8zEy4/7bxFtLgWZyd1QXFMgr7ToR/CtcnbgzK1XL9NJBmQj/ax++xqFNOUeVQpL6etIv4XPqzTDY5o0FXZprSNVl+UXaP1ED2l9FbNE=,iv:LrytpDZt7wOVuA8336yezU3dl7Al8+HzuEcHpCVZLgU=,tag:a1jfO005miN2/elvubiXpw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
