apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5u1ydliC2qbclwv3GgHuOHjpWMWZs1J7FHVY/eQjm/11mM0cn5Ln2hp/hqgHe2DTG90ze8mwKKVNC1cPXG/xhumJvxP3O0rNqN/Ke4LV3kfS800eLwHsD3orBPhRrm6B7G/39DcbJB0SZGH0fjU7XvJKXac1lavdV5M+hiVTl5i7NxrIJJKHBpmFDcTMOWH8J8KFN34OAi3RUyxaT/bpXyllSTfYrDPtbZfi8EEa7JxoDg8FwSGT/1GZurdJqE9U4mpYpddatMJ2d4auA1Zk7qtBPrm+l0LOgGiENStKIP8S61DbRao3LMDM57dnZOmwLMKNlaMIWmMwSeAVkQW80IKlFlqrPcoBArb5qwIsSVULnPXI+Rcb3rcbuHVhnzjL,iv:crPQNyBN0hnaECYmdcEe9363ufoXpkoR/J5JQg+rvx0=,tag:kSqYE80R2pO6eJwsoIbpvw==,type:str]
    identity.pub: ENC[AES256_GCM,data:faYunWjKc/utRcs4aWUBNqPgRrY6qoM3GfGE+2S3QH0yhmUDtucx6jGlc8e/ya3JLnMv3oAnrRuHVWjmcJG5ZOFeXcgUHXlM4mqj6VDfsfWmQ3NNgzh4daMTpG7gB9AHfcBRVJFNARoVSaSKsG6H0sa7rS3cf6RkmY/12ojTdNWA2cjRWyL6S1flnvyL0/6yaXJZVs76fBm7a+8aYLOEwd3AFmzOFeEC/tTZ1p9ElDhkSNK8u5AS9lUYCH5LXxbnYHhaODtUdfPJRF4gHQ==,iv:6R33bKg5C6kYpQ56ezi3zuFDxfA9nrK3ItbX9otKvMw=,tag:+bSxINJivD4xTBNpO6AWoA==,type:str]
    known_hosts: ENC[AES256_GCM,data:I1LSUBsGZnSdQVcIkcVe593GM4gtrvZ26xxNVnIlXzD2wa1DCvDJ+giWUe7lRputRn/T7ijSGdX+vhPcIlQTQVoB0ZbIXJZgxdFOOe2IgtKXcUZQ4ccJybg63nDYwLpEv8CaDWC3H2q+UiaAAPg9aXX8m88BZS0coyqs15SOJOT/1aiiGtCZBjISy9HQdMg8gbybJ6Dm5pkiJVC4oicwCYhrto8yO+dHlza1,iv:9mD6NgYkbjIkArEqW/Hxzhiyk61GGmMyaNr/1A/jA1I=,tag:ao6hbNRjXobk+XleBC6GwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUmxkMDNiRzJnUTUrSUFP
            d1Z0WUZ2cnlqNEF4TENtMTZtRjMyOXRWRjJFCnZIZTM1bVNoN29Rcjlma1YzbDFI
            bnRTRVA0QTNFbngxQmNYOGs5T3NuUncKLS0tIHROZVFBVklyWjdORUV1OWx5VW93
            akNHd3RibFZsUGtBTjNBcDQ4MEJwN2sKve/3G+tXE371v9o6nb5EJwrrif9Yy35t
            I2kCBZpQqOwfw136mgbPGbx4VWhqGX3H1H4+1t/P0pjU7dfRZXCyaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T23:00:41Z"
    mac: ENC[AES256_GCM,data:jlJitdrX9xLFyUF8DEmB9kUIETYXfHb+EWSOfm4pph5TI2uMN667msJ5icp2d80JYEwT5+u0FRj6jWW0TEIjBYYEQmHaT9OAwz0NQbMNa0+Lm6Jd3gznkK19cv4YEoLFqFquBE9NvADIGU9XCQ5JiLq+yaQ1isKHyOH+7FCrIkU=,iv:HTWBpPhBv8g6pUCH7gtuWIA4kdTTaCI2OUfYX96hbcg=,tag:mZPtwfOXKGd67cnOLvT14g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
