apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:N5hXzWmlKrKcLGAiFIbnuX3Eg6UXXA1uvPthlfmkibVsfiTf9TccZbn8OMLBkMMVhfkrUnYPy/A/bnZS5llPyPKYKclsuQ8ZJK/JaWK/vi4dvWQL8Mepc8skJkEfHyEMYcQlPR7MSH60lM2CRQdBX8jT0S3BkiQ6M0pn6R38eY7Je2Cmw28Nt0hZdb1widwzjSmv6s+NsxOV0/jNPyf/FRsk+ZoT8ASrPe76Wh3L2hUbrBEE56mBy2DjWk73yuVkU0r1VTQud0IOKXhDUUn9i/VA4j9M59uGlSTUJTwmZulrovW1soT6uVNC1p4wL7CHpa4X7MYXAP1HHbH+93OGLaJ45GVYKubPrLfYbaQ1XEAJD1W6lXie+v8DxbTdLwiD,iv:G1+JSBm5GZupZmIuSkWIUhePSvfgvba7YuNGvDIB1cc=,tag:S1pAsj8/uSr21Ei4IvD33w==,type:str]
    identity.pub: ENC[AES256_GCM,data:aXNYHQ6URpCuY1PrgAi0xb84Uzz+9NqCPF8vJO0Mo+Y4HD5hdP2eFcbdcIuSwRVlNHV0Z788WQ9VZE92w7de6s9/2Aoizn0YrGsJpnmGQIO+w0BrVyt8MjAKQaTvfpqRrTBo8wcCWEIUjduqsJACn6FrGeCivAmqO3ciyaE2vpDoK+v4ZtZI2STJE+M6GozGJ/t8X6CrRGZM2fPu/6betnMCLhGM5cTr2ACVqHFhf3ETQHpLdesyU7EVuy/96q0Oth7e15T94Kw0oGBWtw==,iv:HWLb2bHjEtBbgQf8VbZMHoz1lZZSu8k1jdu16B1mPJ4=,tag:J2PlMZXHLO9dyMwFjjNsZg==,type:str]
    known_hosts: ENC[AES256_GCM,data:3m2wy4v4pSiwfKJQD4/3hhP2Ttcbcf7BVyvAoj0CztY9Ou3LqVzjCjZgyVRGwg9G+ZbVaPSY4BKnK3Loxdx8z2D7kjyucOWbi6F1pQnXNUBQSehaItX6tS4F1rOIX/Npl3nTWVZstktj1BX98LIKePGaSoZKgC51jXGVuk5NeRkERbS/AEoulFaKKSLDyo7uYZ4O3ZUH3Z+OtJhoR066sWY4HWYfEOapeTTD,iv:l+GRJChb61jpVsCuUuHPxr0nmVwyzkTppVcTYVfXNl0=,tag:NfGZsCrgjN4U/cpYsGnZag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb0t5R2VkbWRFUklMK2tq
            R2NpbXEvck4yT1pjVmhUQmhVOS9TSG9oK1gwClRBaStVMGlwU0xPZXNMNGduVFdl
            TkxyT0FBS1RmRWdacC9VdWY5eFM2bzgKLS0tIFZCdlF0M1pyNDFLMEpzRmtwdm9p
            MVdhWTcxR0pQT01qRW9NTUJHT0VWU28KMEg/D8+Sth1AQcwATPMB4Wj1w5JwiAKg
            5ivc04aX4+MzKjHHjAG4fWr274OrIq8vmRg5T15I7LNiExcegIY1WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T04:39:27Z"
    mac: ENC[AES256_GCM,data:lZ/HhaM3TnRFnhA7rIDYVROeNb6hofnDeRwps5Ycnbv29WNJAzLIEIZFHTBWF/KqVOFLb9Pm95wHubAHDqVwhui386/sZ20YW99br416kYwBSfOT2pdqz2lNOKIdHQ3+iGftjTMNWWLRA3TexuS+W8hpGLdPsSH1OPZwr46u4Fo=,iv:uVopz2f+RDo5xzUBd/VB6zkNENRiVW3ILNuBDqQjhXs=,tag:OJHQWzCo9DwDPfzwKJo3+g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
