apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VKQ5AHBuvT9husyVwT9VJhvUoWtbvyP1di86qPABnCUEMq9T4gxPW+WY+qOKL16csQeeO2o2F5g1GoDP2blzmJpM+XScccYkqbTYWb+N4YSgYn7IkEmqFis7Ypn6Ao9eMZFhNd4LTP4abHaztR/NfS2GCR02q8SLVhE6fK7hY1iQjJCAqnEFy+OjW7NA6O2fY5xphUUOTK2WhrFLKOKU7gVHooNggyR8XL309eCn/ZfF/4ycZRyT06hJcQiikkpi/tYRtp970RZNLrk99gZRJhRpqYcsyUe6Vg8ZzQTpRd+LsGuIObzUlGiiKsOyrD0ymmEMzQlgVk3XglQb+WrCXh0HoGbEPDD1EJUwLwScrkoT4o9qy7N5RXSpPjsB2cVl,iv:D7lES2JRQrgslI85l6w0/Byi49tq7FpUJhruZFcWPlk=,tag:YPVGbVmR57y7jh22g/SuKA==,type:str]
    identity.pub: ENC[AES256_GCM,data:N9nTQ1/svJiZDmDZIpM36K94qyYDJd86Ld2Epn4KCzkx778InJ8+Mq7ASmYGCyXaL+g+cbNrF8X0gpE8M4RJ7CORWFjmXxmcDGdIS7SZTZHe2934lQOGyZn+SSdtPVpJQbqeKOdzr8o1plpp24aAEQ/S/i2ndqUJ2flKqNsTB70uAmyY0ioB6yeH0KSrW/+qmMXdXYehBdcRHv8TMnNS/l9YaiqxWcM/T9Ve7iw9z9sNxvpvhJ5gjmtQ1I1NlH0/tB3iOpqvJEJ26LNdUg==,iv:FvOjFlYS+joFdPseFOIa6OiflJ7Ot/cbfuk6PtLom3s=,tag:G79TWEX05Q4Rs9O2Uy9JNA==,type:str]
    known_hosts: ENC[AES256_GCM,data:7E8POYOaZZbyMBGnSyzmWA6UB2sx9R4nInReK8f5GpuBOSmlXw1ExdHuxI0x0S6a8zaH1IWUEZDk67VDIZFMhFWucGuDRfJo/XWMU+hSJH66FrfG57Cd8W0fg0O3iqNXoLPrirehDpZmB5zDDd9f5HCPLX8A4kcr5W2UcAPPZ3pDCo3wcYy6hAddjY/kQNm8alxUA89fw5no1L1sWWLx3bKSKjYZb5Q8phj+,iv:cH3aqMH8CBtTTx2VR2Xdz+niatY+3VEUjVF6W0bTho0=,tag:WJLI6jZW+MUdhtgwlx2YXw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbW1Xd2F3L0k5eFExcC80
            dkFoOWYrRDRGYTYyWjdiUmp1WWVlUEE3QmlzClhSM0J2eUlZMGVvMC9LdHprSEw2
            RTU5Q1c0dSsyVExwYW5mWGp0ZXJ1R3cKLS0tIG91ZkZBWGtEMXZGR0k4ZlB6cmZG
            ODZJWm1BU1l0K3N6eWlScm9sV3dMazgKapFim62E7Psmsyg07QB6nFtRkCOw6Nao
            Zar2BTAUxMHDu4fgXN7cAIdDFrt81RnWz3EHwRDKFsOA5JwljqtMmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T23:14:01Z"
    mac: ENC[AES256_GCM,data:UpaTD9fpjL8ah9kSIBe6ce2EEmoXDO/67eb9sqKAI7FZyguhhjRpiJh0OKJZpUhXLXSKnoQ3D05ktiIVFY1eKYi/X65DDAoKxCdQyuc7jR9l/owewGjjPoVXTNMtMSFx9kiIQu0bvEbhP1b1OZMa17K7A6BhF4cpi1MvBS3AoeQ=,iv:4ElzFYZSbLQjHjNn2pHWYcPcLeBigjbBEvuf92GwjxM=,tag:hNFjppvBUymqLmUyhCGn5g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
