apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hC5oY9ayuLiQ1QVGuC0zTScEfrWNLrTiAqq6d4dvtcTN3H160BqWPpeZwZ/CPvt1AP9pzkJomiCg2LViXmlj7D4sTj6WnCeSz4vo34jfgKbMdcnny3q+ot1PBcVFxpjFWBt5wnGe9oyfx7wiiWCz6BescgtoZJUCxnaW30l4QxUeHBCUP2396UD8pQz+BNpxn351NEVU0/G+Or5zoiC/lMoUHDakG347n8YqosAgnJBy63DQVnqWTPnWPENoc0e9i3pAwALDXV7ZiRmK487oJszNQ/IUte2I8J+DlKQvgazqssk9JArxIm5NdM6ZX8gRPohjD6Q8rRftdg1OykKbg/MItpM4dyCdiIJhjyAjBaodgzPD6FEVFKJH8g9zC3PD,iv:0ZZsWwmR835VlQTE9f9b/RxhPj5sj/yv8hfMkK0aw1k=,tag:66PEZcOJG616JgvpWrEKdw==,type:str]
    identity.pub: ENC[AES256_GCM,data:VtMEmfMzLCphf1VGU0uStohpmMM6MqyZBI4pNUmj58xBvKsKmmS5ZrfMzDOnHj6sD3DWgRFqnnctv7xO0dRLrCq59ercmLhglCzVInd4Tn/rFnoMB8XlwIoe/uO5qZqiLH4lwz8SXTivxfwlsUjj0temX4MwYIhqtLth0oxpJatynWUzbjhhHXvaeGfczXl6TOZ2Akw35CT8RDDrJ7tcgqB8Rbzw6a3vmy6KZC71DsOFAVI1a5TpoA9itwPxpdyIaXr0NB7QSz8MTZpSkg==,iv:bRDhLCWx3uiaT5LyZctrS63J0RaodsWmnSBPLxgcKZY=,tag:d33oRI2Loo2SXvZNRni5bg==,type:str]
    known_hosts: ENC[AES256_GCM,data:RrrX5zh3pY19j/QXkfLSIzniAvyKFrlkYjAi8VbHFDTzQIgA0xBGWmM9a7HQ7LA+2u/WUUJ71FG4WEXOdE+E7n2nIQhfVliQhS2m3mh+3NNQIOUMN85pbGfDDhOUw/DCxo3f5G2b4q5agHK+jyOhpoPHirLRuv/alKhgPfWs7RP2ZPzntDtLR6CArlxJ7Pv8jGc59FOrxNDNUR5ZvthZaxaIVTiK43M5paQ8,iv:zmEkjbxzRd/Z4pOpq/ut0+haYNZpGnTaRxuSjb67ftE=,tag:I05O91Tb9FVbkq/kmoQnsQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y2VUdGh5NWJQZ1RtTkhU
            RTZOY0hIdXR4N0FGUzl0clJ2UWpQR2RhU1JFCkYvWTdCMEJpenBIU1oxbUtRbFdB
            cXV5TzZpWjN0U01JYjlmY3h3eGw4Q0EKLS0tIHRLTzh1UUIyK2g1V2pzMlpGQU9r
            NEFFTEVPcldxMmhucGR5WkdRUlZpQU0KDGoAuKo60yi+++MQJGPfurQ+hXo3F6Ve
            xjOVpThEj4jqEji+0ymlDAtVR0oKhErhUSs9okXunIdbijr8GSkPBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T22:37:41Z"
    mac: ENC[AES256_GCM,data:HjMMteOrDaPb42tgTurLZyIFaaZLxYbew1kRkAO3nDNasapUzSUOZ3EekeAK2wI6Gq9H450jktal8F4pJRl/vGxNRVbvrRu9yjZZCf4SYa3W6y+cTH6ZTMLoGbsW7pmRkryGRC7rCSAIWozeodzlM5JD8I6jB2jWg7WMBw5J5KY=,iv:xLvKkDPtZa+F3o4ouvkaW8cJFKLuvaipRf2K+Rbr4TY=,tag:H++wDdmH7+M8kVUQwEwGgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
