apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tpWTiIrdGDhxnZc7m/TNGfTqehZfb2g1dLO1dZkfCmEkJO+0uKDiroOogN6a06JyUzsy8kjRfSg7PgSRwHSHsFbM79WbN+/12Bz2zUZ4aQWyjIHDkmzi5JG0izcQWPXcRu5VvR/9bTXhRbAajKUfuScblTVLMuAqI8/7PxDw4ahNP5pnq/Iw9E9gJzO4XqNRJJOM+cBtt3ZKphr4ZwdLgr196r1IDSrhOjMBeUi2KyYAhlbqM1xH0zg04IDs+p2pUe1TNlG6AU/lFuqGGBmlIw48bv5SoKde4yJ2A5Oq4P8tSq4id3SjtzSE3WGwBeL/rAWz3WxUSth3zZoGWOU2ye5Ka7txn5PJYfTiFFT6KpZqbL/+hyasKFcTzNtUpNwv,iv:Ri3wEc9UNq5XFDdL8VMgVohFDWLx5NECrn2ya8iK/wo=,tag:ty4mOtF7nZdJWVdD9zx6dQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:/dtpkeRLQx/Ws2jPhPGkbELw7TBG0vAAQeCK1FESTRXW6V4U9bx46PvJpG+FwhSWAa6ZMO7UBu6TcOyNwaJUsF3nB0JnPB13xYouxpZU+EUWvfZUgkISKBaGCawGOrJuGosO+mNB7QKwiDsDJsOE2QJrCimwuDt0DQdXhoSLuhkHApz2AA3TmWZA92AiofmZN5rxblzNqUAMmulc8NQr/G1tyC8LTq2emPih8VyVO33pws5PGBlSM5yZB80rxlL5GVIehyon5R5qLw7xzQ==,iv:nM3RJ05XUg+NKjJfA/SMhZlAYI8ElbGOlffxYNzbNeY=,tag:mxujcag09mWbNjq2sUsdkQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:EPaa4I/XgG7VJYm+rDZPfPqRmNaY6cVmo4pNKmIao1GMklXU1AGRbFByEabTnYkilcvzq6pJpI/C2IDMLuOXg8V7HUQQ0oTi4eAI5yagHGqxu/tuSPg9PRJF6Y4Phyqb1qp4HBwTTls7KOBR1weaCRBatfSbjsSeIbPa8R6sbBXL7PhQhfEOxq90038o1GbUP0jtN1Ohbq/Fj84e8/0fKT7HS7c860t0NSDg,iv:xLIa3N7PfOmBvTTfo6OnKa9IyS0H2E3NTOhj+IrewcE=,tag:fd6Qfx2Kf8ktx2Pw1cNcrA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM2U3OGtXc3NoQ1kxRmJ0
            dU1lc3RWM3IzRHIwMGlQSjN4RG1BV3FjdWxzClJQUGk0UjVwcjBZZFVzeWR5Ny9r
            Yy82cWdjZmVITkYyamM3bGFES2I2czgKLS0tIFlYNFBJbG5pQUYzZit2bVh6SmIw
            VGhQRWVGMko4ZFhBa1UvSEQzQ3hrbUkKKWxH9d8XfxPTGXm9v/s3kEjF9vqiNtEu
            XsXfNj44TvSlCUXroQkJqIf68kjjKlA1zkpSG+hSd5h2VwN8Fyfi9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T20:16:29Z"
    mac: ENC[AES256_GCM,data:4eBuTfLo8nHkbm/+ZxkZ6Mks+ksoNkFRtWjpWp/+IHQk2w+wis2ZKxu1PpUFk60JBk+/Y65OiLFhMTOmqgrSsmH25wi6IQAq6JLIxUF81r1EyfoirDbPJidXyPsqUZWRG6zH8km0tRvJXgknzHZaMMtQYyRcVakygOdvXDYRFXk=,iv:POgExXmpzYQ0ARAyX7TbleD/l2aFjySDsPr2TlU+QGM=,tag:TS/LrM3JZW9ERj24mT2fsg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
