apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pxAyoSBzEmEIocqOer7eLA3F31xrgdH2btApPalIIqeQYDegRebE95PawGqcQfAWmj+OEgUsqN7M/fFzbYSHx8m14FOnBBoIIzfEsLbMHaCFZIIzaQcOPvQQwBv4gJR9xpTyKkPenNNtP2DWEQcQDnKonGqCmB6g2DRlRi5gr4463aa8hQx5LQoJwt8F1nLc1h+d+STg/3jFd8If8zOtyM493fAAkL+QDyMCTcLBXBlJj301cLN3mkIKMSCc9qUpzA4Vn2cB5PQrqSQF2S/VtYCQXWigoqGjpkyYbTaVjiNvTvoY6gkEG7BNhETUuxCwG5HysxKa6iEGQKO5cC+/kE2AmXq7Nk5YoT4eI1+TCccwCQw3HYNodRBTA8dcc9+G,iv:fTujBIsJJvUHkA9WiqoTy+W4cF0XKGKvYFqk2WLflPc=,tag:MWUhEBp9c1Zyi6wW/IOSyw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Rb6Clu+zHtbFblJG/DB8u8czsPvvBT4UVD3up2qnCV+71EmYDm6EyoJFoPgL4LKw2ALNVBCyiw3O1JuZKC5W9eMWcW3dYtORSZyLjY16vLm8SRJEXv88dO2x9tKwuX10VKG3Q0RAF4egn6rbNl7KHuy4oyLWFwiRHdBdobwnOlxH3EmY/3HWt0HgBmC4EdSt8NJlWBjt18VNOE99RR3ArtLNwhzD+gIMl+YCS9longy96vSi20ByGhUu958i7inIsLYfiFuIG8W/lbOFHg==,iv:Ngeerul8yf8p4YsMHQia/HeTBv6qA0049rbuH7OwyeE=,tag:iiiNvOi1rUugPpFKfWs80A==,type:str]
    known_hosts: ENC[AES256_GCM,data:+i2OpHoFnOhqYBhCwZ1iIRA5FOEoZaOWjhwfUkqn3kVqflcqkbuB58RO2zlsQ9S1asRJDqBRT0n8PBs21B5B5VckQU7CKG/hleI1I+Ob1+OA5m9P5jnKIbQP9uKMPpecgTbvvyzJy8MsP3nn75oRZMhDRbHoSIZPbZy702VNn3r1a9RvW1iIwEGaG0UvGJp3OUnatYn/8ESjuZ9h9t4QpYky4/d90TAGxM4U,iv:JXycjETWs/pzmYnPLgHrnIHzwmDVRap3XDObF3aZcms=,tag:a4/xxMX5wlI7Grv1UX4VJA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTWV5dlNBZFNiSnBzcTBp
            MEpqRHUyMTgxYUIyM0tEbnlyL3RiTnl4VEdBCjJJdkpPSldMYXcyRkJkbnNSYnd2
            N1QwRFc1OWszZHRyWUF3M2FDOFRJa1EKLS0tIE15elowdEljZ3NFRTU1Vzhvc3NW
            dnNhcHNrcTJJc1YxaTBmY0Y5amQwU28KgndXVnN9tEhACccH4g9Z8li5l6CpRAOI
            Kp7mDOwmtmD6ozCE/zHLusB2AazGHi3xYvwNpBpdcYS1AFDzQwsdrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T21:15:36Z"
    mac: ENC[AES256_GCM,data:WPqPfY9+/MGxm8lsjmZ+V6tE4/wkel14Z+w0oYDXZknwSLWqfLvCObCNLSWTIsiewfBxAbbl1SDu76Hwp5473VFFOtZ4JYeHJnPn3a/CoyqZ99gQ62Mtljp3c8NJA7P5xUFuMVpMaMakZYc0zVthIW5afbLNaIMWErblEp0J0XY=,iv:v/SaW1wJMQSfx6ms2lH3fPnolJzjPG7HBJ5BqNjmgE0=,tag:LhhnyOokTnN31l8rb5u+NA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
