apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PVBuhRtHGTfiWmRtCd7YcZZx2UpjOgBW/m0AOr0S3gkcMfPDsizpSV1DB3wZU7KJMoCjyWEM/j3eyLYbLSyvlgnILCot7o0diygfhGWK0ln+pOXUdJHXvsrilZt/0YjzfSTrHsHtx/rt+eWd8iQJRU0ajrar7FPligb9AU0rbrWlPsmWa8b9zIkbrt5+dmVBZQu8EFcDAgCH/Y/i8IY9fiImcmW0mjq7IoBkQGyh0kKDNL3qDYzSyr3MrTH84lQZuIrqEeAXDjpWzRMPi/M3JK5XcUYGyJ1uWsdOCwM3WhsTpTO+PCJt3CibJLJ+SnFC7WixG33yVdHiMLuQ7pfIwlzP0XEQVUuuHsVLIOwE9gYl8b4DNhgKK+/hIo1btKnh,iv:Cx2qXtYjx3g+S3CnYzX6wLzvq/ynQ4fUVexH0Rwvr5c=,tag:i2rakasG26iNC5dr/YVIuA==,type:str]
    identity.pub: ENC[AES256_GCM,data:pkgLRxnaEpDdqR8ljm82Q+oaZltniUqFszbWljfqcKrq1f/qZUuYnbM+Mzv+YtUiiZlrNXETw5XpdaeMo4X2Md0x9Sk5eiKOSh56GiQUSoPCdVn9ox/kJstP2mcBTuyIon0mOMvW7T3Yd3+uku8MYrRIa7MQXIbA9cHpxxsjZ9IMeYitOk/Jw2G86jSPkzDGSwWo8lUqct/FQ0mVa2y5RhI4hkMzNrB+peHCXkBqc7dPlqqdVXX/Rbtdf/4VBX1V/qh83oTsUqahl6+HuA==,iv:X1giikbHdI9l8M2lhLW09BflZ1moSzgt07Botfi+v1M=,tag:rXqhlF8P3br3Dizfs1SHBA==,type:str]
    known_hosts: ENC[AES256_GCM,data:YtxmMtggT2+AlSUptHkp6igOCSLuFpfLUfs7rv/r2FSNS5DGhavp7SQllL5fuMxgv1cpDI9z62xZuwB1brqsEn4mSO4M7f/1iTBm9s5pSE/KwutoSPq0zfEy8AqP3JBerOpnE8aDzyIjb6LtXRl0CNRW1NXhhH7A8ssWOYtKACMUcPOdqCGtPQMbuWEcZ14fWHYfMNUwTuULIcUWxlnrJl0GQsy18WL/4Jkb,iv:6Hlpf5vVM/qWPo1/XlAMMYWBxurHlv3CKG2YNmvYUhA=,tag:6Mt7jc1lbMtkek/gDhkYxg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN2Z5d2hFUG14OU5YL0Jx
            MXJBZWVoZU5OL3dvdlNzeUZqRUZyNE0vRmhRCjhERTd6Y1dpK1VJTG5pZEFlUWQ3
            UnJURWdhNm1qdXJRa2hDZEdLL1UvekEKLS0tIDdsbXd2dU4rMkoxVjZURGgyWjlD
            VGhKWU1kVVdybEZ1SkNHQ2NLa0N6MUkKemwiXQpet7TYn/GpSu8QgrE1kbm4JguW
            YGgt0Vb3qugfWyVMe2cdv1Do33eCeh/9y3B6GVuqU7wJwatYYNwRbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T04:32:18Z"
    mac: ENC[AES256_GCM,data:pzyRrfSi1z1QsezvATHJKUY3DpRw8eMNP61osc6eFDPe+5GF7ROsqTLTkB4lWJu92dD4h4Dm9uHhO5tWQrvI/PRgqzKuH+LxCGLr4XXuyfHPFurUP7fmsoFsJVRX5PlvzTut3lwn6TAQtENKeGN4BeSn+XrUpy7eXak74EqpvL0=,iv:AQ8ieP15nr+erfwQlJCuSQAcF0EVaNCjV0tSJSZjLEQ=,tag:T/7hVLy5OzQtyfGXrfD4AQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
