apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JtTwxYiyQnRnL8NqCWi0mRtbe4rMX7nm4VqZ3Bf2QPhnkxTrpOmQ2zpq2YFpvNYeV7Wh6Hu3JzB3eCWfb+rXZwuUtLf/r9WSBMIdsJGK53e8dkiebs6HOh0ApDwmdK7wMxEO4C1AVWMgWV4q4T4LMzEKdaeJxRs7GsmXX2NaRuMmIFM+STHH0HDG5GZhHBc5/33tB9z0DBB5BSr0SFjj1dNbHHQMb16lt2oQKc+urx87P0vf7wpuHuOcXEA9FLiwj4V4G/JF3mx5W2Sj8FVPVpYBJP/lJSjFsS387wO9eYqUhZOK3zCzsEk5uFHccZgUNEe8iC+1eDOyY4NcS46s+iQFSo+SEk+XbSLpb+st2wMMplIm9dqtqrQs7XMjHpuv,iv:w4cH1lcWgsrmuCcQxaB/gpEat8o2Om4Q9uMlkB0k/1E=,tag:n7GjFp1bbK52b+P3b27dkg==,type:str]
    identity.pub: ENC[AES256_GCM,data:RRmkMc+KopR9t39ipMLSHmg3ZV0wDWak8qUaEOj9i/O8zR1TAqJxtGyeBHzmjp/4/qrSzRoDYCaJtjcZ+rv5GGSybLhITsgDrQvPdHmcX5Cv/PV7zV8Og5f3heJjtY6bXHfL4iOk2VFseRDjfTz2BdsCDV9DWNvmHuVZbp7lPI2P9rCQ9eJwmtsCU4ZvEOgF/NbaXF8D3Rvd4wd8qqTmoiudvEobhLT5O+LKZ6+ODFOTXLm+QIBGR4jNOSsqSdSF6NXefSm5GgvWUKuDoQ==,iv:EQpnL/ElCreDapcay1yJC/xG5lOt8d9BCXAonIZOSQA=,tag:UKRv4/5tMUbXOki6amUjIg==,type:str]
    known_hosts: ENC[AES256_GCM,data:TBC3/gwqcTF1hY1u+2yxLwgDiY59YaJkIafFxGZF/ARQvJQhtPvga6MNYnhkjwISI6UObX40uge30fSW9bzOqc6wKw0juUufMLjPIU24ANePTmr+n3gGRl/STD+8W3T0bCVYB1iFnHwlbZhCZ3mxOuqqDorZ0sEaq7xyk0/UuHEdcw1ca9h/lYTCmmE3++qPtcsAJ78Vb6IytxWgWa4CHFoMNWe46ZWpveCH,iv:IpAvQ/hub5xFdgTwgYHR9dejEwjPlAdTlp7sFr7KJ0g=,tag:+ei076P1T0wXuoG+ihacbw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQjAwdDNZaC9EeGJZS3Nx
            YlVUa09lSTN3WHNwTkpMZ29LNTF4MGRQemhJCjZoRW5SWUIza1BQQzhvRmRMQUpo
            NkEvQkRWclFkMjdZN01HTGEzWjlWeWcKLS0tIERqdGkzdCtEeTl6VGoxMzVxKy80
            amJtV25RS3NuNGJYandkMGtneW80cU0KmLiu03WP1HPYvq3ccOGApeWlHhBcPrvF
            9Q88SobEBHFks+kvbG4PRRxjsdDM+1dLhcJGb7s3zLEazfHRyv4XDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T17:02:15Z"
    mac: ENC[AES256_GCM,data:oZy/H0Min9TrMof1Cl4i8kqO7UiMT1bTZFGowa8zuyBQXdQdBYLKykAMZfe8OP9hQkSVAAgcsB8Y5B+iAt+rN2cXs7bASp20Mz+uSmzhDBLgoSyNTgsdVMn2CRBMeYwhROfnVDYHdNAermc6TmaLkr4AYF1heNS1x5Y7mGzAd0g=,iv:netczR0SEJ2TGZz/o693BrhMr5h2KpV+A7kzIQuOves=,tag:R1fiAOgm1ymIxTwup+rsdQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
