apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2K8ASxLJzqH7PXUnmQvhlxf72B2oO2b0muZzZ96gQp3EBge7cR4dx+TMRGLFUhAqgUNl4fm/ilnMdhOKB4h8XUd37aQ9YBd3rgke28wb5Uruniytq1oI/6hX6we7lYDJJQIjMlHK++Rf/uNCg1mbuy8GyDEO8bAJDhn/gRxSwsmnoazRJEOFmlfV4FBZavXPu77r5HlADzWKWRCEwk1awIAnBtwfXOIjaaP6geyo+m+GIsp8wbbfRygk44TXTuVL1/b+4833N4t8veZ+sFk7aLbNfPj/eeY1yVt+vzDAX7hkG/qBsGeD/oSSDvYdvdwh0qTF8nnBIcjGWY36BYP4dDVzLJ2x/lDMSzIQ/8DVEoBmpUWX0FC/U7dxjAR6WHN/,iv:5SKmwQ/6TlazHEWxtYNicsEUAaraI5dPptAdyN/QezU=,tag:H87z5j9IG3rJyKD8k9ybQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:qhEHsJCPVOcBSGm2YLIwPYV1jWQ8QjiRoPutsGVIXcvI57p4WK9lnRndOsHx8fmZ9B50opVbuvWFSU4c77zXymm8t/VZ5RdCZJQYTBSiAnjN6p+3i6eNuSp8OyfQ+uBhb+Toz5v58+OgiDLTa0FqGd71QtON6ahss8VcxOtsLaTjPJe6bSW3nnqvkWKFNwWm5WOI3kKAMHbyeT4fpbdKEktc5MWctKUEK9SBIqGPJ8HbusPlD3d/cGjU87w9TfiRDUMfNqYbH2C3WQG6sg==,iv:0qkTggWxS03qnCdSy49rMJYzDvF3YssghE0xM/P9qW0=,tag:jQJyIiKbKq4cDBV8nkDROA==,type:str]
    known_hosts: ENC[AES256_GCM,data:DL8kiGAetPtJQeA/2CTNRa9qRfW8QoUX0Ztgf/3anodODMi/y/7QwCJfoXS+IE2ziwtytdOtbHwjZLZrARpuWrRG99itqs8p1inEc/4IOupuDZNvtGrzd7T06O/m03qy9P8p5DEXEXv/euBUeWtogMclXxkFyFjS/JhjOAOung8GRAyRDC7zpNSV7kwUQTZjgYR8YaHS0CtvGK6lc30mGEbU9gqHI5EhB3Rd,iv:su8AXHY3omxHhEVSj9csyfKwCuk91WdIjpeNO1YPDvs=,tag:N1qs/+MCrLrZPwJ0GsL1EA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZEk0RXU0eVRGS2dmaVJ0
            bXhEbVo2Mm5Va0xZbFpkUS9QcDRwNXkxVkJZCjVOSTFFZG9WOStMQklDY2RjMEZD
            YktPbTVlaE5GaW1QbERkSjZjMVBERlkKLS0tIENNUTYxc2lna1NVRUcrMUFCQkpz
            ZTFEWVFKMG9MN2oxcmVMQy9JeFg1OU0KX9qkTEIuuZi5zBLgVBYlibFcLZt0DHz1
            GG0ljJlCEBJ7h8QVh5hwtMkGD6bjLJb5E1M1TvftARmnfLIWSvJqeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T06:52:04Z"
    mac: ENC[AES256_GCM,data:vrDLBKNx+KfojvhlKrge5PCwith8cJQSZC5ecXhWlOIz8Hjg4eNOEoyTLKmuRnehInpjK1zyD+c+wpl867csubvJBhYQMIn8Yi95djTof6f7mVAyBlyhP4zmmcslP+cslVFH5LkYGWcN8Z2WnuoHAGsLpPigi/seR7Iy4N76cmM=,iv:UTb78g9HKDM0rEjcnwPYXy+WvqHOi7jkpx6H6R9E0uU=,tag:1/YQXmZgQXmXFImTes5ELg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
