apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0VPvtMWGVoV+Z1Os0iLLBHfkXfZbha48NLt8Sq/MVwtJVPFwGJB4yQDyOsEJ15pYA3SZqd1TjPIxh7aqTiBgvZHs87UrNxeYI8ABpGNuTvxxiM0MuibNQGEJtha0OfIYW5lt1b4a5ZLt9lUXnEUCx3gqvsTMprWRF6nBLY/Q+MGEfmMklGIeLoTR6RUPuWfLXYllIg3zrx1A6eMEFyNdDXp/rbG915iitSUBX1NKqeM3LNwsGFI2w8je/CA9fP2rAhDr/QKh8SFz9QyaI4hZQ5oibWRI15yAF7Q+JBUzL1qY9mT1nb+M8LyTzWFO9ckG1qBiGi0HauNqLUu0BE9hM6xYvuwsC4pjIzRm5flHyXxd6rrQ5pxznSOj6s/XyGvJ,iv:OHJBTDNUkmJb3w21RQWyic8pDuRwWtQo5kaYN71ILK4=,tag:g98+HtZWJEpYcfItEKtS9Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:5nDxlZG8gqAkYLA+4QhWq0uxvB18nEkJkFjLdEWJT5L8YJwULD15bqsZbCIYGboEeJ82z1lwf2deHgWdAcgVhSniVn5ioUcBx/4P50EBZx3YkrdBXf7PCsm63FW0+grViag5Tcma+cP71qI6AQTa/G4oqftKQ1/mUjV4UIAKwjIEwQ5EoIBGFkG8nta0j5chULuDiHsjm9k2I/So61IiLJuTCAbeA9R+z2xaPfqttFGV24jJFDMWneLfdL/ZHYt2WbFxAOkO9gZxj6YyXA==,iv:3JJTZusw6tVintFlSv2OWBISzoUGvpTGcnD7DTkJ0yc=,tag:it5dms2xgHBrDLDBYkZnvg==,type:str]
    known_hosts: ENC[AES256_GCM,data:8gSPKwRcu4x/8gbFJ6dqICs0vhuL7ioS74dRLdmNXyFRLoV+Ax4QvYdKVzpWOVY6snkjGi5yTgRqLaIdzHFGm/RQTnh8swBP3/0GDjbJ/PIbW4s6hwtBVdU/JkUX8X+BaLlzHR3A19ddgW37CoMPpQa4TPbi6+HBOn7gG9+Cj+hwEEV+HFPo/WqDLj9UQONZ9CLhpCpxJgXsw89OXdM3htGTdr75OpfpEsHM,iv:E8WrTIX5r8Q7fhVdzth7RjPjsufIyFoAGsyg/+pbfCk=,tag:S5kNmrHwyCCfI3ZWfGoK8Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS2lERmNaWWdUWW5RN1dt
            emRmZE5Rd1lVMTR6b2Q5R21NM01vL2RXNkZvCmhZc0VYSG01WDdQUGdYbjV0Ykw5
            QzdmTjZRNGtuc2NWMmlYMXUvQ2o1OGcKLS0tIEhNekZEbWNkNTFGSmg4MVJaNHRI
            YjMrdGtnS0ljRlVuZVZTNVBqem9adlkK39HYJGlHEq0Z9W4l6QCQ95wUM2D41lU7
            rMGCMTEqOshoBLj2mBA/wEF7SlE8Z4Sn36sYBG1SswcJzSx5X9RTkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T23:28:28Z"
    mac: ENC[AES256_GCM,data:6G9bW6OLzvUTSMLaPoyaLsrffW7faopgnWLjU6nuF/Ay1H7vwVhtMrlS9JRrTIEdrOyK7G0TwU8NFKSm5NIsZ7/7T+MqrBWxAp63/NzseevFu7Ljr4N0gOGgseiL75G2Ss1UM2vEaSveUfUJyRfXDYRRXsokckF7jURw9f7Fsic=,iv:o5AEJstWx0SmS5Y15o+ih4+fbVFdSrAhyeGLt2jGFWM=,tag:8AoxBPFYEe8e3gBp7SGlLQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
