apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vxnarSOQbiuEK3Wamj7PpLWzbzzhWFJX1FYfHXgPovoStxp9jkkEUJHBNEijhXb6dMEoUV7RMc4yFNep6OwWEqxRt22pWO7aF5dTYXh2rjmWE1BdMln0xoVrPMQ3MgI5YF++RYlAeBMyEsElQxDqt1zX14nlfYbOcRbnebceaGIRFFLA7KuS8hDYIHZSNUs4+3ShzDZVESUQQCDl66d8KsBIZNqJRs8GJ+83ewRT3EPRVWgMiHoUi0Ok4YcQMytPU/ilNl5WzrWzS2tqNiyBKx5NweguZoORHH1ESjWFUwKWPqmSeyqyCbzv8Kl8U8HIam0IEet0/WtchVN2WkfyTdFBLv6njLa82dMdj09N+lxnHSLjxxCQq/w5iEE/fDH2,iv:r58hm3N1NrpvnFpwt5dWyJylrXMLJezc/exHxF+tKdw=,tag:v+Rgb6mXnnHDCApTtsPOzA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Nba9WmegItih5kqUFxSwLhNBdc21iI+SjNMcXQKWdM0swr2xmy4Oo2Tabv3g4MzZpfJHJPkO3hq+/z4YTTUsicko/BegrOBfawx0QSvK7FUu8O3KEBU1EDEerI3D5QWpTtpgSM9oexJJGkoXSR1zf+VJR8s8urNtFBXwa/jMvSIrw0luIg4jSYrRBQxMRvdjnhtwxSX6hoXNKmripF6yYAV3LgYFRcFynggahxFJ56DcuSSy5K34ykNLHa7OGyLq+ocZHrk84O12ELAOBA==,iv:rnN3H0FEltU8ApGDDKMZHIhdESLDM9jbUDcJpl8IA2k=,tag:MOngfScgO6IBAIaDH8DQ3w==,type:str]
    known_hosts: ENC[AES256_GCM,data:/84uEcZP9/F6hGWGjxsQv50C4m6BlKJ1q9l9J8gZOny/17rLdg2HaxLu8ESAERxUzpZPYtp7tP15cMZsAoZStaHzVn/60ka7bOqm5h5kL/LUgoZ6tovlt5oNtiVRUdfwvyM1HBleKoWjpffnotPPyS16GCg/CPgxkAAd1aawoZ7q3QH6IMEA1H0kDvSIEldik3yja5V8Nu8BbCSUCrziNl7aHA985xBDz8o0,iv:V+TrSyESn6hlvSr+2qasCHWVBQxER82ipX3JMMr+oOg=,tag:90BRoxD7FNA5+GZMhCRMRw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQzQ4STBQU2J0cEorbkxz
            dVFVcUw0SytQRGZ4anR6YjV0SUdTMkJvL25RCk5qZzQrVDI1cmcwdDZlZEp2Nmc1
            NDRjT0UrZjlKL2VyYUVYM09XcjJQL3cKLS0tIG0zenl6Y2xiTFpIeWVIOUFxVXhx
            TUR2bkh6SlRnR05ib1B5ZTRZREtYSGsKcU4qyUmsmmKP50vXndLTHGfxRGnTy7PC
            Ka5Br3KAWNM15/Iv0A3HmCT+VXGh17+Dp63jA3MobWRwo96Hbb0GQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T18:05:44Z"
    mac: ENC[AES256_GCM,data:mEs1i3uEzPRFiHHSvMYWCxREz/h6Ke337gYdm9UODHYX1iJFI5tER+ZKc7QHmeklSZKxF3aZ9oicqCnFSo1RBFYAaxISaI2//seWBN8qGU1dvjmhNv5cvlrnOFN5J1IwuZEpxVuwkC811GV1ezQ+5Y9LVdvw50tf+Rg620Hp0/8=,iv:QtrdePMjFFyHE8iEMHpYt3bWF8aUgS+G3jNLJ/14s8Q=,tag:KtYjv2l7fBONqW4BIOFAZA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
