apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7FZ3sCV+151PdVefFyeJH1Ia87M1cPa1uDu9q4kqRBF4Al7Pz6ZnCMuedzVPdXLYA9NZRZFHksimqhl5PwRi10WjebLYfbDPxaFQFwlhALwvfoJ6zOEhRcsE2VAIyOZGkUovn2pmdkL/fYTaeFf6L8i3oKLQ6xE5+AsYpEwBWrg0F1Tcf6KlNxr+aVHHKQuKHsctxwquN8WIONjeRAyk4B4rrpC7DJpdpfc/2gUT+5AR1C0412Rl73jtKa2d+2ijydlXhBDNzj9yYLDC9pI501vA/t+01dyc3xJSF5AdMeTmLr6kReVSshgymjTU+P0UoBDViSg54vQa0zOhtuL7lK6nRCSaTMGrzTxNU3Swe0H+5oqJlkWMUCaGNatTebog,iv:ZAO6kdOJfyy/DO7tOQp8kfnPfhYFdXgac0G9aYB/Xwo=,tag:AiFtw+VKi93uQKOrelxf2g==,type:str]
    identity.pub: ENC[AES256_GCM,data:48W0aswbynbIfn1k65vQMOrg70c5FbNepkSvXE8/z3I57TBwgPQMxHHfqN6aZ4nv2xLO/+vdC8Vft+hW1tSVxNXXD5Vt+RUKov8QOPexYvKxD3p2TudTaXUDeaL7aihsLVKGbFkbPN3BHLfaFS8f55HGhXeWwdjz3BElo8fp3cXxwonPlpnPYspKaah4kX4kGNp8gIJFmeft/wg1MHY2j/sEuT4C6rLlBuw3KarJl4mQRpeC7NGE9ydvd8UTnqs8msfQygCsdQPs5hLzfQ==,iv:2ciaWSYFJ8oyOMBQSmeO10vAmO7sbJ+BGLUHEt4kKy0=,tag:Onm8pqSXRYcOdA7ww0po+Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:uvea+YZqIIZIgMnuuZ0ZZj3ZTfUzhwRfEXMjeSHL/k6oq7av8e/V91fm0uaFMaD41izkj/6T5GJhZX26b5UO9wRQ0y3OQEHWpo5rEsy8CUhK0to45QBBV1Ljyg6re4WTiOZ7Jyjo3e5XTPteEgjqa++OP/IGIMVwP3hnbs5im0mG+TxLTM5WVno5lYTzIPjjm/4aSszUyA6yN5vu3fbIeU6A/6FSYWJ+Lnhr,iv:JKTsL0U8xAClQcQT+a6+16Fq3Y3JDVEABtyjNACGEGg=,tag:cW/VHie+PdJTRjExyVnBtg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd2l3WXpkTWRpY2tXQytk
            d3A2OC9JTzZobk5NVHQwNHF3aU9xSUFOTGlNCno3VWNPNDJQeEJxckNHRUMvbXA5
            cUNlVHYyYnZObVlTeDR6ejM0Y2tXRUkKLS0tIEJaUkUvaUZwM21JUEpLeTZOY0dB
            M2NiWWR4VGY0dmxKQlZuc0RiVm5uTlUKKYvFcXWiCngONLfhfCEQIwWd5/7uHt7H
            IHojoZDGeBaIDSf7dpNWFEn1h/vhd5vIAXqXtNxMtlMJEGpSZcbNPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T20:28:26Z"
    mac: ENC[AES256_GCM,data:yZrCZ/VXQ+V/ln8SDmv7Np5eCHYRgFJ2C9Nt7nnV0lxN0AE/1WSmNC+OhdP8xoPqhyjVq18drYTe9MgMP1ma4rerw4XKsReU1tDpeUFr+7eXk1ae5wKxD3P1S4fUhg7AhRK+t4VaAxi2w+ffWgf7qpoVMWvgHmhL7PbG6Us8pxc=,iv:fKQlEA69+pbKeCSXRew5WzoDLdyAFY58UY85VjZwwNo=,tag:LIXQRUXefB71f6pHOvJ/zQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
