apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DWJbMexc4a3iwfeI7nZBhc+kUn+YrSCD6eo/WVKUAmUnmGXwg7rG/eGLQSt6yg/ZxMuaWcxUaBt5vuOrPQU2IUaCLVh9JEPofPL/vOJI/u717J+vo4DHqEO8RZph0meA3tDHbKBeZsUstfvrG67gh4UjprMd/oXyqiHKVzHScfs2rarKlxyMbfraWUU4UtdAtdRsAox4Sjf15YtJIRgFP7ft9B5Vl+9ZLSf4YZHiSyrpRl8Rvu8RiTQlxbs8ZHL0a2rfqcaGI644EsqdSObiemt0GvNe+qEOznEE6PIRpnNz/tSpv8X6RAhJ0vDGAYWsh++Vfx6wV7dKH9wZXfX/u8RdzOWJLUdCl05HkuTg2KETDv/5xQo4FqFeo6R3rNdL,iv:LvBwUIcv74a2ERWjcyY9qYNc5P7m2/f5dilcAdq1N/I=,tag:tcw77svLZF85fb18X9VMVg==,type:str]
    identity.pub: ENC[AES256_GCM,data:DectdFfzd4OcaNC4URyV5+4Aui3FEfkXDQu1h9aAHIP5gTWo0i75amjWLLTVOaVAWMuYlf3Y9Gb5f8DO54ZSlFatW5fH9Wzjhu/2X3ht770RuAVwASVEhKbgJNX6ZLaLc2Jjgqaqf3ctLwLo3obQqZAEpy/KfgQCCLiuUcWAdpn2miy+ou7Y6m9qfqanfVcqMalGWEZZZMUeOXkHLvvT3/R+yG2UY1Fof2HfBZ85EjNFWJxhTb0SW/hAgGSI14BtIBdkJz450qp5fVxd8Q==,iv:Y9qxnp10nBuH/wxaGEg1wuKyD0Lqff/G9RAffvZhwSI=,tag:IRbT82in4uuH7Oc+UPa5qA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Fso43dKmgqHSfZxQczf7NE0lfDKIflazeef6rZGRth2o8kxj5p2a14hrrVTTtdboFmvjR3emYNGVtUmmDgMeNtQe+VC6auTzfJ+HpWOlLbbjMC8NnsHjb96teyk7CQCVhIPuCggIEp/jDQmtwedXqgtuBL+mjhb8Tc8Cm7Idcq0DtQ25z30oKarTOWnDcBOVP/5DW3RV417rkVaFHjAA/sTha3p84zjFHEBt,iv:ruzDpFQPD1ck5V8f2GBg3PqtFRBoQHl7GH/KWmS4SFg=,tag:BEusrBvWn70TUx2FoGg7fQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z055M3dNdm9GQktmWU5z
            UzRLbk9IVHl3U21ZMWIwQy9lcmZjUkpzZzFFCnJXM0M3ZmNvZ1NjcGtheUxwYUF2
            cVRlYk9lcWkzVm5ISEp2Y09kWUk0cU0KLS0tIGpybmFnNmJDWnlYNmsyYjVDeVFq
            YXpiNnZmeEhSLzZBMnJEcy9NYXFQWncKzv1I8spj2/SSv85TRo8XTimPoiJdkUj+
            fVpgUC/BkB3XbWxGP0spMVUkPYLtkp4wxMG5jhcCZb/oW4Qls6Hrlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T08:05:56Z"
    mac: ENC[AES256_GCM,data:6sawmRPcACHfbGrZOxB5kJsXjUvtQ43YOYBPBgx4sF9eKOD5iAI5pRNB7nS/gi2jsr35TKXJMM28/Kq3MxYwnOdSt22ZhSEabKtZ8MTTrbt2tcB3+eeZ9EAi/4GRVHm26Et68fsPrv4bZsUPnHPVAFh2n78miEcdfHrlO7pwVdI=,iv:KkJWWYIoJcNzCmxXvFoii0SdUsQ0h4l+VAezHUZB+GY=,tag:5zA+c/ZgUJsnfXWyF9xxlA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
