apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Q/iztmHnwVd7iQJz6all647du7M013oBeGdJ/y4h2iaXD8ePJpS68WcJyskBhh6Vqukj8mOWaxbewuzC8sLgVO3dLiy4eupe5abukzJMDEeRoA2T4SLnLEcafF0ypq6/lE11+/Ptigd1XIYkafqcvC7XTtgQSqhN+DBN6X5xtoChePJAJJpRFkaPbizz35pR6fao45oZbcLsAoBO0uOYd0gvtACX20VKTAPOLlKrbZ0diaFh+ynvmJA+a0tGWhE7jXlX9rsn1/btFaixIwvmYU5yQSyn7fKYotI0ChQ0C3BqpIYoNmKd3W9VCV3TmNxuTCaqZLHojTWwnZtTFu7TbX371+IjFe2Jls5ODy0GtP1Q/QFt/hIQ+oPQs6MXvfU3,iv:L9t2qn9lAgsvln10vuBvDlu0DoGDcZOyEqdhE3aOnRs=,tag:LvZS6UZNgjcmpI2342pmgA==,type:str]
    identity.pub: ENC[AES256_GCM,data:+arHaUe0wztx3QIc+q81rG6LZrFiMDzsjJZLMxAhP1o3LEBDe/xKcExAlod5rPiWqxeYXqNambMCGlDy0sshSkafB8AbS+Ej2q6VW8KxgEadlQ1T29Y1wne7mqJMufgfw7Ad1GVpt35GhyRs4kqW8IFyyhWpAHKvJV/iBo2oBlZAxEO/MBiua3sDW9MhilHGEWV3OkVX7eYtdyYJrIUXXaPfcVl4y7mphCO7rH+osophCyS9HqXpiHThUHEYCnkbvwOTGmRnffzXyyQrow==,iv:hSZWDQX8TXExZnYRFH4M1nun1QHSfcVxnsA6lL6/A8I=,tag:zmrw/twv+jxhJMipWQ+AbA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Effq7tfhODEOONsRzDY2Z92+H8H7HA1ocvW4LnHT/0phadRqcEiAalOT8jqYmycyYDc56+nrrf99XSGN/30vCkDyQraEavKQBw1GI5iGACHJYQEekSCZbE5QAgf9VM1Uld2NGf5ep0Mx454x3qwmv6W3YTLLaI/qSpHoeoJJf3aTjHzlLwT5y2h9+yGg8p+ULZrq76VOyCTk9XhW4Ly759D9CewvN7t+xrU4,iv:isVS4zmj9CDjQ7dnvnXuMRHJP8etGRIFmEYazz/sOyg=,tag:Tu55CfHEh0JkdYT06GJXNQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaG9qc25FMEZXdXhzWmR4
            YUJDLzBWVUoyOHB3aVc0djBUcnlsZVNSbDBJCmQ2Nk41eXpHZ2FWZ0dKOUhNOGRs
            SkdLY2g4eVpKbzNqUnY1bjVpdXppaHMKLS0tIE5VaFA1TGF3L3VZQXcwTG5xc1VL
            SDk0N0I4UUdQNmpUby9pQXBwQlFabjAKE4izkXhcxD8NMTqPCFmFcQtweKLtVqrd
            YmvFeqNonlBHZLRLXblkcy2n8kivNAltRQblQBsVFWvrEAE6W8QtFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T02:17:21Z"
    mac: ENC[AES256_GCM,data:VwLfDmEqiSnuHNQCBYuq9aWgiyi8RmCOcRu6GBXF7Wcdj6GO/1ka37d9Th4wo5m+FBCNOHHSoAFvx2ChL2bS7neJEx/Zg2M3FSMtXbyXH8YzaM70A2y9XTUNJbrXLT+uF8//QTPYLmyLCCfatrexYxojjwMweTTKhHjOihY3rNo=,iv:qtQ8UAIIg33iD54eQhQAPa9YxGU5GBpetw2trwXZt0s=,tag:DbbGpImZpG79g15e9MTpwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
