apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/fkuOvNVs45NeJMMAQVQZ+S5TjvevNrq5UPCrt+UDgKW4pysK6I5guf8vo5IYctuKcWWeZAoT7SvokESPK6HoDQ2ZHZx9DZUuotQPVdIx+hqXjtAOyRBbAXmlYBKvb9k1P8GnxjutU4e5LNaP0u7DxLB4hFG1ecjJfEdHyIlYkgam+eRVUD8WQsDzH9qX730jVly6PWyyZu7J7cQKcwJiZYthZLQlcBPG31w3mUSI08OrmCVE7CPcbGQxw/j2lfn9EmMmLYj48awRwQF+prU8yB8r93nI501AWChGSoQDIRJn9lLhF0r1reGXVyxDuto7czUHb0ouLcFpzUi8m4UgXgdRVL7NshxfleG76dkZxBZxpkn7LOoigAMol/MphJ7,iv:3QxTPwzO9YaAZJi7lt4BcOaS6geWVn4O+7lKYzyHnvo=,tag:mqylFArlbLEoJKUiO/pcgQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:aMFxuyDrDsVLDxZO+E3Rqj5wxrqquFf0hLzBJ1+HHyETVVithe5pnltiBXu34KaPAAcNFOluiWtIETCH8TBvKuT8hW6kBaXfX6mrOkKVjb4PBXaImdNqkOcZoTJhGmEv7LtpOokW9vmDv208KGpvcd/HGxTK/03FePlBTQFpjnMU2Arbh7Xa9nJkJtE33MlDJ73H1np0XchB6YgOo2bok1rG6avctWDeWPHBb2E877g/zTN8rmHfiUOmGs8kEBzFgVt7XNu7GH8YMQqVKA==,iv:B/8QOqNX4ZJHlMSdzEKKCQRqn2V6x9F4H1on5GjB8+M=,tag:eydcpjXO1ftprf8v9X7Jzg==,type:str]
    known_hosts: ENC[AES256_GCM,data:PaLh/350Fs4d19OoRsZpBuVsUw+M0D6pWrFxH40nYT3HPFOcIdiWqwT+DFwRfpKM4Lb5yuprGJInZHT3PlK5ee+dbhOyDYLDDHX6bWfam2vNZKoDj6wzZJs3tg5vcZPleyjyfi4CYtcoAZVx/eWBC0q06zSUiuhbedInMKBsrrOVbCAQofeapsrRXkkrZwVw3wctERVEWmmjviLVs2PmiCR7iSxvSrWcDux5,iv:53K1dNVcKhrpLS9EJjbLDse6XrBhoDuBswhyvyneatA=,tag:RCWEIXCAD3urvaaklKnI/g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdmhjZ1FLUVNkakVkMTZO
            bDBFZ0V3SGQrdUV4Z1l4QVM1djFrZG1LQ0JzCmhISHk0S1UyakJPV0txS1M4Sk0w
            NExYSDlKQ20rTk5XRHFHVnYvcFBZQ2MKLS0tIGVuVk5raFlyVWg2Qks3Z1hQeWlt
            dXhwQTFHWE5aRDNxWjl6VW41Vk9KMFkK/3IjbFeM7j9ShIEvUZhNulc7ZkM+N8B8
            7pbjcWOLd+GKDO7cS/m6LWENQIPSG2stqb6gxs/ypDJu6/VhvOHRRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T08:27:33Z"
    mac: ENC[AES256_GCM,data:4CnBr4DSwtTFYtuzBYUY2G8vFsiWEwG3cZtzMywpz2ylE8Z1odNVrHArIAnL+yZQjQkNUHui/jwiI8WvuAwzUAJc2OLdef3T5H+bfed6X+Hp1/t+/27bYlPTAM+Td0avaK1EnqqbyTUbg0vTVaQ3sXR33N5L1FbQ5aziwAMNC34=,iv:e7sFuO2T/as57GSUpU2wtE3LVJgTX/5bIgUplBsY34E=,tag:tvw40fJZzwzsjKyh52NWug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
