apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PHyjvpJO/ZnSIno8Bz/I++P52ixYO6QQAKx1ASv9KNjxCeJTI8GiDUa1ypvP9d6kqyBkm6wJIgMVv5qg3QISi5ADle+jE3R7GUSCva5D4hO/MDip1iYLu5w0mnRK1iq0xLf5emnTuYMSux727PjV0cgn0Y7CvGq0E4d4/b/AKf7y9YHzLmw5Vp8mh3pm4I/6PjzEwSAZilQLU/j0Had2lkjgxBypaqJ2hE6qh4UvZv80ZJ9j57OIob0tgl+uWbiGzpHsg7Ogt/EOvGa3/gTsABpCvW/Wf55snugEtobE1uJsjIOERRPIYDDrU/FaXpoUawzo8AtPS6X3YdhHpzhJK4Gxom5JEdviJrBnhAN2kdPq1Z6ypKudTGs9Fdc4j7ZT,iv:uBe0k5e0eL+U/W+FZ3Klnr5g/ubKAfbinVpUavo7wV0=,tag:QqsR6o4W2KCSNyj80dnygg==,type:str]
    identity.pub: ENC[AES256_GCM,data:RdmPwiDuS+ZYKD/rVDcEocNq3J773nuSBuwH88WAUiLtaWNgvyIvQkKsnNX3kEQ5KS9Grv9xKDXkSqIvVGNuSVZizbmXyIAdh6p7UtNsFOwjHZVXgW3XmtyHLxT2bpS3tFa7VE4loHSLKmjfZxWBCNndAiy4A/fkuCmEVpN54H9Xr5B0pxqgFjSyloNju8oXyfJMk36zyQkVH2+AZkHUtqvbtTYcQ7RerQ1kIARapNlDSZWv3z6sKuA9c0+LNJ2YK2tDnwPMr+AaLtK/LA==,iv:byXZozPVOMwz6kOCcu6KkwDAc+6Jp5qQij8Yswkm9SU=,tag:h992PtuwTPwJ+vOCBCkO6A==,type:str]
    known_hosts: ENC[AES256_GCM,data:5vqASV+z8FNQQUQDU/H8ELpS56CvkIVYFMTclQdjJ6jSzecNBnQ07xOxRXMbTCFrPdlSTxMT2FlGZ1IeP8mWCer4EZ42saaC1DabaJ3l7L/Wyf0yTL16yh51zXN+0I0HpjD7irGmiSkea+dznDqRfEphZBQWWdVNSeIz+/a4XPpMXpWV3hmTfnVCc96fF+LpLE+jvEuQSWJ8YHnmuHn+xKE+i1N10LV5/wyv,iv:PjQj2aClB2r/0wwifUG1RA3t3Nsmc+3K5pW92YY2QZY=,tag:rUI2in47Wmnwg2z/qqDjGw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad256Q0MybWMzd3RCcGZk
            SzlWa2tMdlRualN2cnQxV3ppanF5NHBUV1hrCnhWL1pJQVN0Y3diZHJrVUUzZmdx
            QmNQb09DZms3VnZwVWxhRXpSd0loVncKLS0tIFpEUUJzZDFndWd0LzRYUnFqbDlQ
            UGtyeU9HRnQyTE5XVUgrdTNzMVVIbTAK08pmSXD72lhkWcDC8lpJp2AkHXRJTd15
            isPcCYopNG9zX7HF2mMCUPshVkPMszKo6rrqHkBzNpcmyEtADbEnOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T17:22:48Z"
    mac: ENC[AES256_GCM,data:cl/5Dc9n8pzf3ZLOWkV9atx/usLsF5VhtS7BkdQC1NuzNnHt7YIC38LK1aD3hwqN9rNm7YVyZmRQX1DJ65Q1uaCPN17SvZE54Cwz3zDVOMaVD9vi3hkFhenP6OuySlXv1R8sC8nA7wHUNtbv7L8+I694cSSmrh5KeQhaKGYeu0g=,iv:zA4Rpcb+VsNQloYqQjwRiWIInaBC6SLu5/Hy+9DXDso=,tag:FWiC3z18+6NcRy3G3uCuWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
