apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AYtEfObl0rf2L0tUFZSV8Mff8YvGKmUo8n3IY6+13fbalJukUjpgxlu+xPkNAuEdaIQppzSS+bQuAmONmp+Ghzp20n7oT1/+BVRs28jE2pCdvXQjWshT0ry18c1CSfJefJLwq1X3ndUAaI2uUp+ThfjSH1kRUYfZ7Ply32oxFlc8MZRInWgmnwUDaW1f+WqDL0D/00pQQRuWyVuF8ey2K1j1ntmX4PZrJVf6gGbpX07XbMKbQT373Gaz+LszAA4UjjQTAO9ULE46tCTJX9G28VtBts13iGHOGJnipRUqHS/4XOZXD+mR6JdMaYe8UTuIUON7Mcu/tzsH70AdU75r+JGE3n8BKgc350JknqNM7q9usaDG+/41Btwd2fzA4sp1,iv:reAQvH5kPpSNFJbCOgnOvJg7KZp3FoWD2uDbbfD/Em8=,tag:GuSkNK9d7WPhWFVvATVpVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:oT6KgDDLgTrQWO9TgmnW8cpMKRH8sOB3wbwzHHO51jAF/NHKpNi2BYiQIP9gIEpiYj+gFRcnsmmUtixIPvzl2fXOCx92rzcB2n0PVzjczY8Cqt+RF61VbFvUaUvFGEjz/EDRCpyhWQOmZeE3I8futRbBY/c3uxD7xtQQkkO5QODti5bBBZVg3gSgtZ3SIv8IMU9mkvXwOQRB+E5LiSqghyhxO6CetgvmieEy/99OqLYdJlJN8KpmF/3xpjErtM6pjDdVr+V2JnfAgYubXw==,iv:Dri5CEFzCG2630pVTSDj5H8oGVdALBlCqViunVfmawo=,tag:Q0PSnT0OsxcZAhMUQ+zMdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:wPAGPG7hRa9BvVgnfdi2qkNz1Mt6Y3Xpb4SDBhMD6R+QGptEPZdM+Plxzk1hpnsjK7BhJlaXVNFLnye6zn6vWRLVXlKoBzawlGo8jSqoMNfvdGteOUHciIdgFAkuZgZxArzMRr2yubwcZrKwzXzdSB8NPU9OFTVJ7axNbRb4rXRQwD9v5bunruSj69R79QqTo1QJWhllS9yDG7YtKRtaSmgaB7zavAczFVMk,iv:DEpFLh4qadxvemqKSEbVK3nKNj2bO7yMdosDOQYY8g4=,tag:By+Vq8VVzutPm7NOBp+b0Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNkdwQUdvemUvZWphS2F4
            NEJsUW51azk1RXIvQk9GM1BPMm9YZEpTVlJrCkx5MzI2S091Q0J4anZXY0lTNXBm
            Q0kzMnYwZ1Y1ZnRZV3pNeUZPTWR0d1kKLS0tIEd2a0x4VE9KUlNCbXFTTS9HNHBz
            aHQ0RythNjd3V0pSYUJDd2h4ZUpPZGMK+4kOfZcx4rBeV0EQWwf1lda7j313DgVO
            P3n8kgqQ4yEYmn29NufqlyFDLXWmvmqRUARZykFvCqwtoGY1OZe+ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T21:13:22Z"
    mac: ENC[AES256_GCM,data:YczCTFje6FRe1rEdbOKQqzcxYHXMBdcFKJLoLcxR6sC+kJBEDPZr5DL91Hk1jDDzs6bkM+H6CdxAif68HJdEPaHd0h19lYdl+dp0D735GQpEd22+lta97nHyHcCFKk5PwaK8/1VhKLpRggMQflmyhxJkBlR8slS3hsaNH+kq7pc=,iv:5oPZPUaJiGlVjGdWePdYWknrw89V7SwaI5lR3dhxz3g=,tag:LawUoWNcOs14PHuU5ds9XA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
