apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qXwQgVsmbheGaNltW1v754rTqwcSesKFgJDxHQcoKbe586uFNCiatQcTL2jVstYozZyKfNcpUTGfKfG317xvd507Q5O7JKfr/Ro22MnfBlls/Jm1oyWTbO+wleusYgGViEXQHl9ZrZipc1yLZ7q4OWs4JjWY2H0HvRWDbsghgdAKiSllyz+rszov3bSQC3CMo58QaEj4IoreFB3TN9DiNg5uFyoI1WJvpk/OTXQlXrb/S8R1qUP4Cn9Gp5L8ENWeG3Tx2L4LATYq6oOBNqAc4VUmyHNMe+qMxuSYyevW8af2RpC1edpkF9a7WtIFm5vg7JuUlXKF1o9z/D9om9Ve3cwabjFSwS5yV+GcJeDnQLSYmImBCtxYEjUFszlBceVc,iv:N8rOi7ltD36cXLQD18lxYyZQDEDGRPFl9EGmcTgOWv0=,tag:vPnmSWSQ9815pVMi15rqUg==,type:str]
    identity.pub: ENC[AES256_GCM,data:fO14hf0WDuOiJ/vrceX/W5Pq04FMD+IdDxcU2jVjO8o5bj3xLsMVB0T1K6bAq2fTgTQ+rZ3AgcXunwMr7glY82YdQ7tBP1MxS/J1HqByKRaWaFqWNE+Y3bDr540oQrfmKn7Wo6d4JdLkUVJEBwO20VrIiV96DOHmRwFwckTFUv3ENkxyEXP9hmPKqhkSmLEpkF2f/F9izOJrQUSf4sB0/5lqN07XIqxPAbAVKvftcdbqbV7RdheBI1D/VRC4SA8LrdK09GrU225PJQ80Rw==,iv:P5ZEIuinaq4nyqCK5pjpz3plxf+U6VC2bl684XNx3xA=,tag:CU7BQ6W/sulPy44Bh4Ssfw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Px0sYLtXmF3/CLZ0yVaGtjcxTq1qyVuJpFQGk51ohk4LLInTAjQBBALMky9hEmDvk27V4eew1NohD2D8Da8FY5MRXV5fKYMylHaZTJZqFUZRwOqyH6J4pnhiHtE+qYhyrZcniFZ/J3LNv4H1K1dE7T8YxgZoRkrM3jfFHX+HZ6wJ7X5W8yQ+ZQ0rcWNau8HXxUSkBbtxQC2l9WONOenThxg49HrGQcB7/hME,iv:M2CapHFp43EpFe/R1E6JcSr9E78hfaG9KsXd69sTQBo=,tag:Ch4SHlt+xATYvMb4YuNKxA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQU1czQTZzL3N5QWNHdUxh
            NitjZTF2M2JMQkxIWjNabmhpcDJUTCtaZVJnCllwQXhsZUZRSjlpaWNCanB1MmNX
            ZS9MZkpnemNLTkhKVTkvWW5FUTJmL0EKLS0tIDN3b01NWm03MnFQUUpuVkV2bGd3
            MWxkM05CL1ZvZmgxRXBWeTg3Zm11dGsK7OaVi9o7Ie8txSqMNQsvjmDeDDUOxmWf
            nZFNlHFLPkqR9TN+vXmVww3p7hXmUw0hy26eUquy1DlYmU0Sms/obQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T16:55:55Z"
    mac: ENC[AES256_GCM,data:OcM0a93HsFlcSwDrZnEMIonCvqhYIzTLvOmd6UOEnjniwK6Xc7Z8DoFAAMD625e1n73e+a4vKjDzlsucyYTh6FFW/dRcBda3w7EMveYQKoL37N4T//wAIq3JBfpRrbw1/wxi9b6ATaDHvQiSYdqX+q5jZfT+xMcpsz77CpgFwR8=,iv:ARkXUZGQpBIsc/cNuKpBkLP4QVi798gmoF7Av1PzEho=,tag:Z8O0XT71pjCSFA5QxVWhRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
