apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pklMly6wOweqDNg3W+0cPwvu2GuQtpPetyB24BE1j1IhQWp/VhnNBtd0+rOT0WjQAae/r6zAiXwQiO6SKU7wps6i/PstrNTCAQL+vQ2cHZ12cJkoPZldR4R6gvBpRJfDUOPsOMgYyXGUYRPHsH352PmAPZ+Ug4ruEFLuKn15dSRxtodWH8sKIA/IZj8FWJYrTd2BLReynvqOvDgODxpmTTrebLbwSWCYqZx3PUm+JB87aFXR7xOYhC2jeWL+AANoYSsl6SCG+/DVb2Ize+dUjTmUwC74TK8zWzFOsQyitv+Z8ekPKaZ23hB/gFigPCM22vvponA1YhF3ufaJ9lrS8fzKMZiUNWXVzAWhvnRvFmcDLwvv17mbBcqIDJ6AHGQd,iv:TJr6xAPxVxkjTWTdoDPrHUbzITUFCH/y8ve3iZn29gA=,tag:/Rv8t3FyQVhw5os7+4J8bg==,type:str]
    identity.pub: ENC[AES256_GCM,data:UzibPo8VS2dkHB3hcE3krmI9ngLA2nRh/BexDIz985QmUSlR6odk6AOmcYFyE8OLzLYy9uvuReOUzLfb8qiBYaUdLXVHoY8x9UzxHdPO03sAdlnspSrB78YxkBp1Nto/4lXoT0gSi3lYlwQgZ73iX7lc+PQo5t73p2ynmNdAl6LZ/5nh2jKz0wSt3T/XtmOiqM70ZFY1frQXMv/wm+v9xQLEu1IJidUqCYsGpA5m51RQk/UP8whzJJOxV2dVMH93hGIAjabY/KKdhfWwRQ==,iv:6UHjLkH3HjvqT/UDdv4DAw8Do0o9AQ+Siuow1IRO1uo=,tag:O1fAwFB0p4owh4IayfYpsw==,type:str]
    known_hosts: ENC[AES256_GCM,data:wYlnaFv24/zjg36vdHGuF0Fvwe3XnVEH4ugvbYr2kx4E49oPzlUUgjdw0+tOWquY+NST14GNquh0NSknnfBRuZ3dRfnlTu9WQmYtIozSGp/bHzCpq7ewleHr6z2lrZMYaAeHn41HaoxCXEMs+BHo5HEhx4hwhk8GD08HNe+Wh0LESa6VWxPb2coCHA/wBHr5sIvQDVPjobvqWPCJkMMDmxegMoFzK1xNoNcV,iv:HF1MOsE4xqyTefynQMZ3RwWywOforB6jdiVacfYiRUk=,tag:gAlB9m+7p1vEMG7yX1p+2Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y2kybTg2blFtVlV6OUFV
            b01UaEpmZWd1MmIrT1hsUE1JYmlYVnhoRkdNCnBhZ0tQNzA5ZWREVFRLVzF4cyts
            OTVnejlFTUE2OHpFVENKalNxZVRtVm8KLS0tIE40UEZqTHZzeGYwTCtvZEkraFRK
            TmI1ZzVhbEFrUktwa0NWbmJYVXN5bkEK1YMcp0qgKOQL4ValdNjuUeXYazbPLRnD
            J6LQR7ohS+a8PHzO90m5IhbSYPyP+xayKQ1Q8Fhu49LTEk2uhKTUGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:22:11Z"
    mac: ENC[AES256_GCM,data:NhGhzB0Ool3cZkwETVWpZjd+Yy5Awbpe+p0C8B7IVth8oGEfFj4CDppQR+r0RfXCWxKU8w/u2tq+gmaTw0u4I7MTw2X7TBlQrf0DLVNaFC9uke0+p5QBJDLK3gjqqSryk/EFv+3Xochd+4ERw33rDUw5PTnh9OZRrAHQktwvyUM=,iv:C1YISgZTTmxMnGQezb+VJgeytHn4Fb2/kxxCsC4P03o=,tag:nWmdGIfU6UTZrDBgfFm73w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
