apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iacPLVTzof992r420qbBvDQ6xI7dA2vq3CWVdiJyCDt0e7BXuLI8k0vV6aYx1VuREQvsuLqL5mIdxPCYHoFor43X1z/j2VmLXeukuSfrMEusbYwgoSJU0d+iaUvu3TgQmXow0j3ccEomTwxJmjs0uwNDG9O6tM5QRr3VfSoTKciDGAzHYuFEDC4UWZ+y37eni2RLZVP08EDi9zDxu5CZ+OZUxMYwFsYttgo0Tg5H5CiAHErziQWYJw7amWhyYYiFgT/TCQkgzQqlQ9Av/+8tx//LrRfGHXZYf3TLmFkmQnUevVy7rbd5pL1Mge2iP7QXSBaKysEgEQJ4RpZnmSrZzaAicFdejlF+SB3+pQF1tRbwOXC05ZjNW2eJWVJU59XB,iv:SAfUSTnwOrw0QhZke9CrWDKDj9G0NreMPvKPRnvZk4c=,tag:LDpYOTz1jbWx5bUApfp2lA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ijoTyVyPDyyeuKNalRqvOkIUkaW2KfBeL9lEtj4HKUt9zTdp/s9Y/6laan+9ZLZr0k8ClW0JCqeMGCtiZYDPbV+CofyP04l3x8URrM5QLersTXElamLzMHyB8N/0pQ/kH5rbnITS6XilQkQbwVI3nfcfFXk+ht1wjDdQ8bLbl6cTTSw5O6zAsD6C0fAJolSzQoRiYNZUVUMWCShpLf9dgzS7kM04R2kvm6TQHM+L1vQP3rMljywmq1Azsl9Ir96jM90qBSLSjm+7p9a4uw==,iv:qEjlH2BC7Ld3tnrZVGWzXlSj/XdW9DOGwcym+XEK0e8=,tag:mcZzldzjaz1MDF+3S+NGjQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:TOsHbTtIf/abC0ejDiC3spxec4aI0K4igEFxbe5uXpHhrSBSAh1Lys5UCJY/WqdqqAOiO9U0kL+PAwOSeSfx8MTFErIO/0FU1r3RUz7QewmHeqN/AKTlMYGqF8iiyzTttnpNt29Ok1ZAofaWBmBpa5c8v2wYz6shjdkObzpHNaT/9Z1KBQdplH+5e2y4roPqWllouHZORgAXpCtYoiMbqXHzDF7LFSkB6XRp,iv:udmKNBu5jV4jVDADta4KG5Mw4iLuF8/NYQLnx+dlicM=,tag:NmS2Q9F+r9C3uWKkua7pLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UmhYbmZLV3RDUUo2ZzUz
            dng2cXpCUkhZejQ0NUc5aXdOS3YxaTdLREdBCmViZDliOHNlaTJHWDNoeXVGZDhh
            L1lnYkxVNGVjV2Yza3pQMTdGSFBmNFUKLS0tIEtaUS9VcHUrRkpDVDhNcEtURUVQ
            U0llVStKOEFjamFYdERwdGI4bHZlaVEKdNxlTvNAQ/BEqtygPbLEYXf1A58tSKS4
            +9/lrxg9bzWhpoi3Bh0U4ApoAWCFPpU1nKcFCIRshMPJqYVvz4pnUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T04:54:16Z"
    mac: ENC[AES256_GCM,data:lH8Ml054ZpFCFtR/MLr2oqtwmBE7GmO0zNAAnFlaG6EIbpgG65pOiS0ZVXjpG52f3e77vI3MBt1scF8KtIBP5WmCXcbp/6LFW93ZY4uA999dlKtmxOdw737yFI0N9r/VZdkfdS8Tn9zi4dMDaIcXvio0ZdIokDn4vdfXpZP7Z/Y=,iv:4u2tDSmE1I19ygJZmhS6MQixEy+YZIU+sQGtk+cnMmg=,tag:X9ThZzAsNAPpmNpp7aX/Aw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
