apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0eQbuGYQyFB5nm0T5HygOtPGYYAQUi+3WKNb2sA4xDlnMyp13A/xxFcmsiHadDfjH4ApJxz47e5UQDcsljmlKYqukhSGV3X3FNLH+vuLaMd481VBCL5r5aWWpn+D7Dgbj6TiE5R2x1OGawtiDzmwJmYIgs46362HucKIUgXeK8Cf1/7N3Wl9az6INk0c41hNmmsOD9rEaXW9mHcQqiROghNhjCZHgbZsNPTzs3OEkBnoG+QQUnYO1zEkhlwl3P2kKxc5BzueYX6kYqxBmZJO+77fdsjwq2Fyxxq7noKa2HvrVtwjJP1KULEgUVrpFd7bf9N+YR65nIDPzW/yi0sI9PBuxMpROfi/DAF0AzXOkZ/qg7m0H9Ocn9SnLWAkuKLh,iv:xnXjsXW2u9GBzh4pcZyIxzYNbqtdgRBKZQ99edmrSUY=,tag:2vIJKj8DMaenGt4jx/NBtw==,type:str]
    identity.pub: ENC[AES256_GCM,data:nvro9mVRlnUEZWRpXhP+cXLOrwtV4P05KZBPA781Qi0hRe1GkkxPh0LVli+qon5QSymyJZx7unLrvEifdY3t0ZaFMxX7J4QNg+N9oCgrAHLMSdWpKZnFO8c36BilGE7x412MMiB/YoodLku61Xr4xNtGqV7h3QPXbUE/6STMn4NxOY4cO73MSVU2O8ZBt0ngm6xf5rCpjR0rURxW5cBGV3ITp1c1kXas+3rgloeCeDgFWSat1kT+pujmQpqgmWCm6Z69r9A9MbnZwbgY9A==,iv:RsGDGVqFXg1xkvfEtO2f924HD7/YE5tjdL681LHjrsI=,tag:4uiTLpYJVGvHhBqkpJtYMA==,type:str]
    known_hosts: ENC[AES256_GCM,data:gRxvMtlh69HxD03nXzVSF1uc8h/EViXEXt8pNLGQx+UcZ7a9mvFNHFvjfh2P+jEBTo96pe5FehyeMgCT9ZUsibZPHnM2s3jw7ORuPvXj70jt7pHpyFpwoHBcK01TiXbS98ZJkF8xePFzl4bmvo85FIhDIK6+9ofUfuKL54oihLLq2aA3EoAVE8MnGd+ACjFTqlVU+ytqQnvxEZCsgJxMxswlI1xrF7eFChC4,iv:g4vjmc2cMKAkljwq5qZv8xXxTDFLgPDVDNFrNFPkhK0=,tag:e4mnWl21PWqyhFtMaCQ5YA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UWlNU1dBdjhXZC9sUFBj
            c3h6a0RQZXVrdXJIakZGUklFdTJBWHgzamdFClRyWit3YUdZby9RcFF0VGpyVnVv
            R0hxbFp2NUFxbUdwR21raWptT3JoV28KLS0tIDUwRFdGbFhscUQrazU0RlRxNUlj
            emQzenJJd0JFa2tncGpRdWQranVGa3MKUxPJRg9a8HukJFn7KoHXb8pW+JpdiSP+
            JwXPQ+Qjt2KseVA9L80F+WqJpv3nDJVSGtH3Yv53GIy9QVHUumFRNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T05:36:14Z"
    mac: ENC[AES256_GCM,data:bOyKuMrw8MdthriUABCGT6xS2N0n0iHzhwYF8eJaWHbGhn5G+L0Sc/thmk1AkZLB+9ASlWsgMdGBQ73LCPE/6/bokWDl+FXMVVdt2WkfP/geDmaKDHUzfnk10CzXZ8bPCdpOwnIv/8K+vhLVs96Pdm2pqAwKhl7OxWrLY28ovqw=,iv:5UkJ9078WXVAhErkJUVi8d/NhgwW2+o40GW9gF8Oxc8=,tag:Mwj405DvGsqfTMt1kD5lCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
