apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xXqz9xhPTif6WPTt0LWRAqrP9UpMk/CQ9AFkck559dPYvmEQa2/2wqLv97sVXuEXpU7nt2FBO+iVBx2nvat35UtO8t53O/6KfxxE7umMvISB3IkP9pQ7WJ9mQjpiG3LlHZlowjCEzsFAs6FMPFOAcVew4c1kdL9iT6dCNGC9D/YgPHLK1EBEWcAeplpRjstVu7R5+UtQw8s2Cvjy9jhrVkWlWHfReNpEmxFH2Gm8DyiaxZFBa4w8EKe7OYiyMMbTSSqUEG2a1EcJj2OvyQv/V6YqIgVRsz2iPVWmx9jtbzIiq5MXUNJd2lHsIMdSel41l0WvR5jdMPE33bqRc4QAIflFjKQuv1NEXvbF1bxutDheljO8S31OmpAfG0SvngsW,iv:ishmjprQp8bW+eUBRC6vENWy2wjCBk8GVAHDAklGJ7s=,tag:BVLcXjeJsLLDuLc/LEswzA==,type:str]
    identity.pub: ENC[AES256_GCM,data:jiAx2RQbNBVGnxSUoTMzas2LMCf+gKqAo1wEE/GEKXm8UsplCjgiehm3T7nSreK9JXVbIXq8Wgi+TXGuMDlMLRiJQvfSAckMVVVTltC96ub7HCC/i1Mtn3BXIL2ELtbgaKwdvuyXCcQOxMBmsPuMzEc931Z5Q5MPRFyrwnFgWVfrfpHJ/21bLzp/37CwHd/lkRNyx4Sd1CIGRHOkIjNwE8Vw4vo3ZN0A9OaZwo5nQa9giYmYMXejHsqMnSHRoWmzDQ2jK1LaZATfDVCCDg==,iv:fxiyso9/eyvTpqsGMFRcszHywW5oRm7MKQbrB+GYpYw=,tag:vxBy56WWJfsYOaMhnmcUEQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Hlm9yylJjJHmlP5dsFlQeVCz2d6/nQfJPpU7+qSJjVWgVOvA0gSkkOhymxtwn6NnUk2dnASO86QsJpnOgeei3AcoOuxWKs8Vy2OyosIyRGMHMrM6o0nEJigymYn3UDdqUokbeXsYeTDax31vFhTPPCItRRvniZXj+peA9PD/i0eq0ACcToa//Z39z/MQcewZ7QhaTHe/t1bzz7cEbfiVrMeDmGAROSx/vSKP,iv:pSMhrJG8ztnFIdL/OKKev9uOSze8jS7jsROSqTha7qo=,tag:S7aBCEDIcWxDiYtR+YbRtA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UTZDWUUzNmQ1SlNZMlIw
            K3RCeDl2TnR1UjI0SmdndXYvNytIK0xEc25jCm52dDkvbzZ1cit2VkJMZ0ovZnBj
            MEZ6dS9xMjNLaStkMisvS3d3eHRjWEUKLS0tIE0wTGNsZThuM1Q2amJncGxNWG8x
            ejRqQ1hoQldjUDBTTFJxQkJySDRaMHcKzwFqk0s/tcK4avF+ZESrYlvCdHs/9BvY
            hy9SNOs3K0T/6+B5H7S3EIZfx6OeiU4XPwgQZTTxCJCN1U+AMT4GjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T04:16:21Z"
    mac: ENC[AES256_GCM,data:PJ8yjjaSTXtca5A9xS2KkWXI3KUIAxPfGb3KZfOmEtmumeZkhgyiqJKrSz3pq/lqfdzeaXzQ/LhuoOtUcC+I1vd71A4xH0eSNLUsntX6QDIYxitqKQCAKXFe0klR/Dq3aNjB4detfdgRsJpn0paeYk+ukE3RXap69EJsVMZfZiw=,iv:7iyExqYl2HYnCok+NdAU4tEei451aZBBr611SHyrfok=,tag:Bf/0pCcCRagIoxhcqjrPBQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
