apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ED8QWL+B20uj8b6E92z1HNt/mkt38JCFMUP2RpZan2w4WR4l9TVRP0K/TzXkcLBH7vawoDNi+mVD+6q0KlshzPoyXJ2sCQUtV4wtiF0d2W12lQV7QN/+IN0oKtHaEw8nZtBuPOxG8Khea6E3j6FYyPkx978jSJ2IfSYGu0vdb0JCLiPETqADGJG1dN51XIeVfQd0jWM5lm0BZq/HLq6zmTaQ/2iRzpPDhjRsMAZDd6JQ7dx5OGNoSX9jMLJ2v4Qz/IRaav2qSAAc1TDCM4LbKs2Gx2leykcAwyAY6zTfirIYh7LUE537GlFnE6Ni0fyeY1J0D8ffDqafOeI8j79K1DBcuaTJzU5wtR7ms0dqejaf6fArmLGAfUOkAbTTF8g5,iv:dfNSc2HBYBUXAi6Cg/CcPK7OmzPmXtTuy8wZrZGIDww=,tag:hTc5jyQW2e9wSjyqz6J97w==,type:str]
    identity.pub: ENC[AES256_GCM,data:RcqvAe05wqUeX+v6KTfKbyMFosjHLNIRPpA7JCRFlfZlP86WJBKQIaQ0b/iMNuTCw7eOveNxsc1ziIQfqjOjIAslGX+sT/6Ybp4uIXOZ8xhs/SBqbrCQsJgQwzSvxUcTuE09Sm5bfxYotdiBLu0SeMO5t8FrH99Rtk53K/t0V5ItZvbU1xGrOHOMe4MW/dy/mjNsg2qsh7wtiXN3bY17F9YplKTvMbt0z/I87bcis5ET3nPvWI/QiIFkkbbrJ73Ev/132ElvN4k0qnNUuQ==,iv:3eTIDOrqOrN12pLYcqMUcPBzhrzOay76Jq8+MTQ80Io=,tag:KzCHlIlD0HrfAv7rXbJF3g==,type:str]
    known_hosts: ENC[AES256_GCM,data:zQQSBpfQBBi229MVl3pNLr7aw5OPWcNI8OlpYuh7gRMBjJjo1x8q9Y2VQkBmKIyzZ2qcN7xM8DIKdu92/9E1hAxmEvZFQ+Ks2HAzLDsljKQaeqOheXt7p1rnHO2N8Ct8asF8JIqLHTYVe+rVJ6+hlgJBsppJM8D5qiLevF793izhvpRxGNO/7MtD6AO5j4VHlKm/CMyqyxFeQs5Mvdstbq4QGAo7YF1B05Q4,iv:aU9h9Yg09/sdJNEmwUb+r3RG7wOMPHJtXNiS5PBSq2I=,tag:Z5ZFlM+1VIHl7B3ehWrV1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMWxoTjQ0RVRGcXFpRHF5
            dDl4UkRQWi9LNVd1SzYvSmhCUEp2TWVDR0d3ClpKSTZyakpIcURzODV4NmpqWU9B
            YzNNcjFRclRPa1A1aHk0bk1rMHhjUzAKLS0tIHZlS0JZeTAyTHFxK0VnWEFabGZu
            MVZBZE14SStoTGZCOGJyTHJzYkxxVE0K+QwiI2xE7pm6CzDll0bDiGnkIOnNClGX
            sYODtCNqKt0WBR7Ban/SF0wcQPM+f/5ACsD+uyQ2sELmfzDanmxbRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T20:23:32Z"
    mac: ENC[AES256_GCM,data:57XN07+F1pVQQC9qvgk4HEqbfYlNlopgLCjktl43XXH3PrD380fCcdT33luv2M+hqq+ctWilncYfzuq9+//uOq4P7w2IKCnA7olrIkF7NVY0asMKEwV7On2Vnw+gb6saflnVFyiYE195Gql5egQYQxkgyk1MA72T2tfBAuo0q1g=,iv:I/zWoH7F+DTOIajWY9Pp/fFgqA6OA1x26EV2B5EL6Rg=,tag:Wl4e/g06SvuBX7xRNkK8Nw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
