apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dUJx4p/ULx6iQurIRS/IryG9SDCskhCOFFzmTvbya8a6nfZmvw5F267M6w20c09HOuV8i0xiPeKGYKbi2XmWRYX1rqeN3th8+s0gTzkVwdsWP7ANRzGdurJjaAUmtHNJk5HO+SA3ns2TIIl7mYOzO4akOtxwKCeRX8foYOWdGF4XUYgFDPcHtzyMfNjTzhrpNDQeDWfcGIX+MxO5NjH6ivNXAxQ2pU+QPy4p+BZsAgjhuZ/APqLIMJlzsdJn41bp9FchR5o5u2HayCoNvFl5G0QfwTPGo1oSX+bziVnCJ6gh6iX+Xvoj0ge4TUkGEKEXEHGvwbPcNZ8AU+bwavZtkXVLFn7XLO98lMzl/co81ER2PfJ9ZZwzsGIHkef64dwr,iv:KHJXAp0/GRmCUUQ0pRpy86nR//SqwBkq/GC642qmV4o=,tag:Coye0JaVPcy3POpt34n1Nw==,type:str]
    identity.pub: ENC[AES256_GCM,data:2xBa3TPy+8e59eNKo9MDbLjh2p8pwYW9Gtit93rYAJZS7kS/i9v2xsWU+x6ilenD8+iuJ07sXGMDGE47Ay/T7k5HjrLO3O2ZCbjW5yRFesOLfGfKTD72t/DlYkOUMmPs4+/wNwEZJfoMFO/+tD9yLDhKzZZNOvXIP7uJ7AcXygwPxYrDqGs9QfTp+t7qyB/cyCJr3PW7vYHlwCuIVTOhwNmV/b17Ghmd27mVTeSG3GZ/W6IaUhn9Kpvhv2aYNP7+OCdKdPnZTKwvVNOhaQ==,iv:OGqy71PNLvx2JSUcuXW5jPZTHWxetj1q4Xb4Q0b5iis=,tag:bw7xUwRuKuyuGwaIgBkD6A==,type:str]
    known_hosts: ENC[AES256_GCM,data:VBCASvRUc3TSeG0UmCQVIn9ZAcnMHqpYJjN1AnQT3dIdQXZxrwqa7qvf6LvBJYbf0yHqbbw35q1VwKcw/uu1WiYkoavbBkf1QwhF8DjgdQL2n1G6H4KAzg3IZ14FIXSmNBOT7qwhBb1WRegj/9fmadtQSUZUizh1GQGa2Ze1saRIBO33QcRtPr3DBwYUk2PbMZwCLQbdfzaM6ZdaDX36V/WHUTpHM46XnKGj,iv:7zXo23YHmCtKVtacpnvcGZtKJ1E5H2gQsxR00SZ7yBg=,tag:i2uVD+3BqsDh6lOrs1QY0A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV3JqcG91S0lVTGtERXl4
            TGpJeTg1ZTlkd0x4QkJETVkvZFZUTFg3aVdBClNXVU8wd0NKMXVUQmFGVUlhSnh3
            OU9HQ0hLQlVyRTJsT3h5RjV4TkZkbWcKLS0tIGpETzZkVUVJNlJpR3M5RlVqQnFx
            bjdtNi9OaVpRUDZ6TVNMVnhtN3BDclUKUorFtEygd3eYMK3Oxr5OzJVgd++ywQ/F
            fuiDOhI0PKI4d3DwMrUP+VTZnyXDR0PzUPLAs02wgGqi+3BBemUEOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:26:52Z"
    mac: ENC[AES256_GCM,data:fwW2X/NOE0vU7Ox5uN/EHDoeTDnZSj4iBD2xmIyZBvBxqBl1trUMNwC6i+yEEoBo+OOnmbxwMmvZ/mKUuJWl1bIu0h4Ebn+F2qEKD6oVnr0Wby3c12TbXaRinL6m26AdHsV7GJIs6kPUzd4cq49rn8omj4ClgiJgdKT9YFR/Mcs=,iv:9G3//sEKdwL6dSjwSQTtd87IS5PSvQQfAtrt+I3nNSY=,tag:Oc1vkw6nkxMOWhftKfhR4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
