apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:A0oj9ER71dCjfbD7wkknOQKHZjZXzfOrkHTu3/DthXEIhI7oweL0Zb2XjHoM42u+lVcCmFy0EevV0/7sjfAexDSocJqvqfeydL1ZMlPxu/ZrJ5SX/YDt1xpkYuA244Ihx87gZMZj2B6zzSz2i1z1qlmdoNyDtBiI+A/C6bpVKA6oNCrx2K8J+7w8qw4CcNc54F7LAgexG2icGGFnY/f+nR+2haKxSaNxwJvUCyRAkFZN71pQOmO5/GU/Sk0Ads/ffF13pVwoFjZtybhR+EXCEutvJS/gn4tu1l2Z6+IniKHr+owLLbALUxfTKuVqYssvzAJBQUKKlbfEZ5uVLfWMOOHt4SYJKyumDEtWD2x0GO5RrKZL75SpYYTcfkSD03ju,iv:KVKjkHfkSq+folivxE/5GUiBJ7vOZOUL6CRVUviIing=,tag:bXC+zINSwFKkxlgdobxU+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:FlMEdgjLZRDLRqxg/rEDBg+bNF5jYvkBOyAMt/9Kvh/DT5Gch8RB1PUo1xUwJnj3AmY8a9N/ToKv7GuCiGux9NOHYYuBG1aMjkLOPV3rvxKzEwJb+eIjZCyR5enqLm8pSs+QvDo/tqgrkQG4ntRnQevyEE/Cg+gdyq9y+4eW95RqMgWZnB8pk3OQTccHbg+npRINKIvUfJmwGD6szO/MHTpvDdy6p2j9j3JQooTvjuSlWlPzDgQwzoXToD5wPFOtmlv2iSAvSAmAARfgFg==,iv:RbVwUz2ypc1OMuj6lq6hyUqI72W3NnlS3bKUti5sXCA=,tag:RcI6vx0/nXGd3XsstpWLzw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ahE/i+6khxMoPNEPBt0a7bJKEgLavzLdbblkDe1zA9C7aur7Ij76jwrupsHTEanx59OyK5KCYc5EoUDTMMT0kits/KC1BSeRv6uxKV9cFQ7LyUc7VakWfmyqyaK2lP3pCUY8d4qqw2riMuggsPPJxYnHhTCxSnt4UZEk71kSxN5yOUHysj5l3oIRE2Sbjpd9y5hIfiT2LOTjvGv9KNUhviK67F+0WZ5JYM9R,iv:iw/iKRjAPwD2e/zhP2beodredhLnG3iGlQ1GC2Lkuvo=,tag:xWgWn2oeA4ptvX4Hk5QVDg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdmMyZHJBVnpKQ2Y4cXpG
            SFFwZnlvSTlWSTBxK01RdzVjMWhQb3ltUEM0CnAyQ05YTVhvYktndS8zaVFYMEVt
            Y1BzVGMxSCt4UnI3NUdwMzNMVWYzK1EKLS0tIDcwZXBVdURadUJrTmZZam5iMCtS
            WVZ2d2thMnRRMmtOSHBLRWQzb0ZFUDQKgTDPa6dQlJdLSAGwuj5njg50fVD2O5MO
            QH1l3hGajiOtL0PBQWKmsnALRlVEtohmw78AwrOFZpYkBjTDFoiQVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T08:18:25Z"
    mac: ENC[AES256_GCM,data:RsNz6zaMOQ/G1+IcTqljiJ2+KL8eCr0IZT0fIIRBPLN7sArXQgIhGXM/slda0LwDQwghMsIVoKNSp64NiVMgyE52HxkDqtK5rBzqMndoOgLpkTCqPajht5kbx4Wh71NPZrJLy9kH191LuwRqVLn0AAGo/zyQqBCAA27FpYOH8F4=,iv:J4PR+SZGfkHyDSqY8NH6vmpjBKUMtdzZwQ97CMvfjm4=,tag:FZvPMQDNyYvl96i4/8sOFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
