apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:h/dk14m59BTtNvTfv0CoI07wb1HmQkwgBBvkqWiog/pI0SVNO73uEQrMH1HdwgwFz66b1AtrXJ1T0LaIDXo0UxsX82GZHWo4yaRM9Wnarc34e+SiuR8XlE4O9TtGzkGgg9BINGpzY6Eo05jDYp0LI6Uh6ziSfCG35F6XxCX66QwoYh06g2ghlP6ig7ZgXGAglXQ7XMTE5QZ/nTTH31ElG/mtF+2M9u4jotPpKHoTLbVWGANHl86PKd3XErGhTndv2WNN7Txs/BpfFY663sSXyYea2rq4OqTdtjDCqOW9CM/plxreY6taU/do3q4uMy4/7P7FweqGbcyU5ZjlRnsd36lKoUpsgULRK1HlpFPQWrd92zfP/XhEOe/BfklTFjWf,iv:yGLG4EE8TGAN+bnkyHGuV1hA7MLYnp6oImzST5zZw2I=,tag:alC0r0CeHePiWkh7OnUquw==,type:str]
    identity.pub: ENC[AES256_GCM,data:p/TXLt/Q8v3G44bcIkMb2NXnN8pHI8ubLvWmc67ThjZdzRPk7j4HPzDjiAkyp3dktaaVE9UuBPgYTJRJ8BtE1/nwcLmEm30zJ8bpov63dAy8ye7asJfCP/f5/QtngoB7aZuLrwWlHN8XK3EpPcEauL6VtsxLhUJnrLHPLeJ/0BwZTt6GsbW1iYnqJ5b/hB9DaTtL785vqxVVJ0OZQmFGi0LD9KSC68Nay0++b87jKY8GRUEuvy7Ckf/31exrj+b3j4bRX2nenN5SJ8c7uA==,iv:wtOqrQf1Cq0zEV0JrU+wD67iAAikZ4seMh3zh2J3jDE=,tag:s+MOslL3Lh7se6WEcNh7sg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kpnItinnsusldIPJNzuuZC47hqmaz5jKtOHxox9+FeqoXwNGChmvler1049RCqsFQxtwS9bLlSunyFTgXoj9B1CEerB1KdLLCKMy/YKWvX4012l8jKy4Zb7rOELGtz4e98KftEkabkKq8t0dT0e4gioDGFwLTiPtMzeR9u4wvHwZYDM0VauoUoxwIMte2PfZ+kyj/7QU43rH/ST1GoNOuMiOEMj6Y3hNUTky,iv:JdJ6LMuRTxQhZsojiKu9NdvXQ3OHwQHOqk+VX5UdmXc=,tag:e8UPNpxXLy2/FpfTOEFF2Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOVpKUzdEVklXVGJwZ0dP
            V3RqZmdKcThPVk91Vy9udi9WY0NnTHZTWGhBCnE2TGxaM1Y3ZDVqdi81ODRPMG9U
            QXRaTmtTSkhJM1NEM2U4R1p3bjlCcEEKLS0tIGpyNmhzMVdYTGpLTW9HZEJWWE1E
            ODhEWS9aOEhiQVluMnltY2Q2d01XQkEKcMMxysfz6yPH92vhbOrB7OHKQfjR2Tsf
            pdjSoNDEHklhRbz/l8p/VMd5S/HerCH+kPMDRZ1dAJauzimGehMHQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T06:45:14Z"
    mac: ENC[AES256_GCM,data:mZ9U9NtZHa5bSKyEpKKbfsZF0ugW14C5IMI1wHugk3XGpDDU7TskLfVX8vJ4yUF9y06aqaspzU8Fxfw395VjnQneI3iNFMTyX13tZ6kywEtImJlz26K0kyXlhdOKB8eYwscZSopGdGL5eq8ZlikavMKma3EdYIgk1aSzpb9NY00=,iv:CfRwF+ZwzkdRy+uh1hxxWvne8kfAc8rWymUVu3hn2nU=,tag:B7OR3S2n1NKRGParovlqOg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
