apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ojiqh+N5ijCEPjwAUE0qAnVS69aBGarQEr6Dt0APWWKTbyJ6PybeTjwROoPWtiiLBo9IePx1WQx2r7AynaU4ONPwjmA775yfCGgm/s1TBddZonTsxUv7ubL/mxRoTWDWF+fZasAhz8YTEwiJksR5CDR6b/Z9WrUZuUOfYMpuB1W0V6j/9NnzKB3b8RNWWqdSfkAXVvjtY0F9SeLfyagBX+CgOeAyq2v0lne6qT9Z8kpyK0LfNu1i95y8weLuIZkiqFdBOwUomq9LOUgLK2Il7kWJnfdtSP2hNjkGa2WMixq7fI1eG5QI1smgu66xeBKOXV7Cb+LPX7LattuE9geIXEqdxJhqQgj/zT25ROnmCqJCvehLDzzZ0KrTLDkEgtTS,iv:jYoMubFl10RQDKGXlOrtyxwNb2JiXZo4wqFXJQf5f+4=,tag:VS1obFUZ2LYCPTjYigGQDA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ylp/Jj2SU4dNw5tRjFt282M9MijbUIEoL9LA8w2Yk/fbLgBmv6DYBvrcFx14opO7EML5P9t2+fXwYm+PIlQzPl9VubP90CoRJQPTIDgNsLmXeMUmpHyx+oiTAlRNDG8jQcqSKvl8WegaFDUSNLbOEx1N7dou7O1tWAmI17m252eaKjF2W8hqqGja+pDIV8ni3BXXilBk0r1CWR98XSLVPesDTMzXZ9EEUv1+MpsmLysYxNtVyofrL4kRZcUrU0ArkfTBFDM4g14q4a38WQ==,iv:AE45W/jNfdDRoU7xhZwo18QE5TkcXfp5+kcsGIc0yjw=,tag:uK9VObSKV0cXLOvJK89+cw==,type:str]
    known_hosts: ENC[AES256_GCM,data:O+yZMlPk+ewp/8CAw4X3amkXxYXMbnRSPxWN7i4lze7gVoaAf1UgKzjMhPpDVBJ+ougvVCEKp61JHqMXbgOy3FZB2VJh+17IP2zz2QF4usQBmSkx9ZUtQSfnvxpjoKoZNcmSiHZzcnDQgUFaoT/Uepl3co7fGtIbSe+WW6tYI5MBcYW1DR0eoXMpbwqVYxFxGvRHPZJuCnZ9IM9nTbY+eP1GKDRrJ5X3GPCu,iv:uq+QUUrgQbGghucPjjN/hRN2dwgccdzMmv8xvSVvFNw=,tag:+/ZAkCfR7gx+iPlfvNoYvA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZzYySTM2dGdYdTVlQzc2
            NWtuNW44UkRjaHMwcHJUQ3FGald6anYxZGcwCjFYSitkak9pRG1YYkc3Y0k5OXYr
            VXVVcHhBaGNWblV2R2sxVlpKMEZYRTgKLS0tIFhqWjFvbnd6UWY2eXV4ZEdFOHhY
            anduemY4dWcyenQyc08rU3hGa3NOVDQKUMgPo0Jz32ZPS/I23ZRHUOYDUSqiHddc
            i1KYDJN1NlNNTraAudA9U1t1wR1n0NMbXAXGffF15rl+RvO7/BWs4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T02:41:51Z"
    mac: ENC[AES256_GCM,data:nmKmGHRttdRa/zLRQPpVlRwJ6i98GrsNkJUP6fQix/nr4bMER90IAmATWc+WXweF1DxOZdMrN4u3vO2wecL0HFiwLI7D5JArkYdWOL7soGtRL04XupISG/Kd+t6VF1gcCEL70Y7MWcBTbKEFrQLeSqhhZVafza6dfSHqeEusw90=,iv:wzKTIJ3tHF7RK1gMg4qGKg7l0Y8dw9IFhYf1ONCnwaA=,tag:vH4k2BcYJLvMUrwryhwrmg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
