apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:23PgohjpIkQISVrGI/07xQo3gNtsX8trpkBTFXtvxvP5T36d65N6MrvEwgQKw1YCf5DEGHqmyRXd4kZZAFkWEp3F1jUoWrAGkJilobzJZx9Pn5LDr+uQSoXUa5OMef0satMoBkCxokczbn0m4tzlILOcDTXGgn7naM7hUsPmP/hJpZRJ5wcvPeQscQnaIP61h8Jx5CPG4mkqulys9VO0tElVKl6Gp+OSQgXFGUYRdAKnGvlaAppL8bNs5wGlG6PspsYKIymbYqQ27Anl0JgW1ztJnLv7T+O3XSTQr+Io3ed4YyBDd91P1REIowe6vFRVpv2ioRzLKY42TyAbtgh4SHD7BN4w/sTEx61r12+hgFsOn1BnLF2WEWrdrmgDeMut,iv:M6JXSHIdiAf/Fy/hDSbosGDD/3LJ45LTPNktVLIgTpo=,tag:D95xQbFVC8KeURAiSrSGQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:SvqiQDWkKu793/T/onbzQXokRwyERvSXcqv8eHoUoQxRQ8RZvjBJWFsBtC7nzQCXpssEGp3BEk/HGNxYHU90XCXaJB3X8QuBvGnPzwE/Hxd2fc30DagbHz3ANwKAzd2x8ekJsJnFpxwN4plhdWKPhhaiqwN5npDO4Ur+KEWQGsluoxALKz20KjhlGzm/1XKDDvjseErOKAVtOxpgj5snjnzz220dCv3YN4BtF4ay6Nncb9WpibFr/EazkB/CB7WwTocAsDcTjzT8KT8Geg==,iv:h0AAnP6vDPQ0OptQ0H9Kxp3D/6vYWX9mBs+vpU7iSao=,tag:wiRaBUD4BUPtAGoUp8ezug==,type:str]
    known_hosts: ENC[AES256_GCM,data:B+lTFqE1tZmGcM+tdFWhNWcWqR2wKkIEImfDN0ETxCcBSVHWDgj9AUBtuGtG2TiKjCOcr6vt12a+59tQ+Ftzgw3+BHHqklCYAD+BLn2PIAF2l2edmxGSnF0fhWyM45hR/I+lItGmfgRFhsf7DP8YUigroKnsyW9Dm+6kkWBsUgOCLQN/hf0rf11H7Un/vzvX0grXaAWv6dk/yiLAwVUWE7B0O9wfeFR3HgSp,iv:TWFSuMAEsanif8LjdkKemxxb/lsLtHTxH/L8yJrm9Ig=,tag:kNWMkNbmeliK11Xw+Efk6g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T2hvVjMrVElpSFNtOFdN
            OTZIaXk1a0I1cDlGNStuVkRpSVNSdDI4UHpvClZJd3EzVDRSTUprbDFaVmZoRjZx
            M2lpYTR0cFlNTlFoSm5vSVFMWkY4c3MKLS0tIDh6V0R6b0Z6L3Z0bndGeVBFbVJn
            eHRiYnpVZjdKWFFqZWtZRzVpa2NXbE0KJMX1bxCB7ti5k+cyJ0aBpSh1AWNoHLSb
            VPcnyQ24OguQibyqcXbeddxvTIPrYkRPnDzB+9lAuXd3YmwqQ5NHaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T20:33:08Z"
    mac: ENC[AES256_GCM,data:ZW1GLpIm/lPUs4C1Wwkdawkr/Wu2mQuoAaKW29q8k/WGTmUXEh8jVbU+COL4l4w/UWaaDN+b7Lf/2kSAZkYebPg8zh4BKzT6zhxD1rwSRJEoUoODWPd02zqHk3Yo5W2VEfM8EewWqhn5g57ohQdtVlTl5jn4dldOBFbiPrzcBUY=,iv:lZVb+xWzgLS3SphJcYhOz1F6qTlYGVUsuQR/wo2Wx1s=,tag:YaTL6FQzfIYf7C0ziPCxkg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
