apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JqWl57DmMYTeFyt8asd60UdSAfLTVsZSWT1Lu1q5ORA33p0aJKMHDts24cpAliE0fBlFR601KGL6Vptg7VqHmrJzkJCDXENrJagxWdahtVjXB8ERksrEvg36iorZMcxCG2bKaeuTGBM/4YIK5lSSnI0KgKxyJHr/ADqomLX81Y4e/KM0JL7MJM611nAJ0vXrH0E39vzBKrCZJjN+lNofVKHMQOib/EI0O969RP+FaJ3P2LKz9G4Zp+mkVHHKD8z9rFjzC1Wb9NcFoTWuAiJxJac5ZANbiOk/ap+H6Mbet68bn4DaVTObFc0TppIzWT2efHE6rf7hIHRCn9U3Owm5GfkETuQHfyWYWc4n5/B3VS1elitOMeVx84EMhZy0Tw7P,iv:0+nTrNtuFRjbAWQsWv1dizn447yjcxxgb9Dcev4CEsM=,tag:bUryTHsYyxhCdu0aBfgABw==,type:str]
    identity.pub: ENC[AES256_GCM,data:t8O1dwlCMC1f1SgtHL1VG8kL/FarUMbjBZZAwzUlVMF2zOBdODgTz/bF2DxqbQQtCTdylU/sqNoLLDYf0GWz0qdI29yAFxnqz9NA4n8ppb9y037G8A9XB0vEkMBtFlrRm4nfFcVpRDKM9wkSF6PhbqpwJxLdsNFjdhW3oCEuZs4c5H9YofAmA01JGhArKXviGbJHFw39P4YLdnSuZaNLAH6uVqJiw58cgG3voD4wTB7P10Ftmw5RnvwnynfLeyxRchwKhNdjl43SMRKu/g==,iv:Dg8TKULpSkAtpd5GHE5FHCI+wMmpJer+vxTz9XCZh+E=,tag:YSWpueLWVpMKI5GhF5Uo5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:RUqYwz+fZLwKVSk+S2140A+9x6rCVPnclYuJCQDmsDDJzpZ8yVnoZ5IZ5uQaX2AK9Jpw3xcAnbq/dTIBtYdaApp8pTpJys43kJCh3JMlVA7W9vYiuskKf61MWFE59msHF5ij4RmFZ6QG6Z63n8LngW4p3juuwXXk4BYg2C1FKYNQjcG47yxAbV55rbJ/TrpZ08hOiTarIMN9OYdcoc8n5zilDPkQ7Uw2Qt9z,iv:Kw4h9TA9PK0PQYXXeEyK8r+e2GwNdsC5GYKUYHHLP0E=,tag:aJOHIGK1Os52v52HmeM0fQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ2JxQlJDbUZ3VmFOelVl
            SEVvcjArTHZZUVA2NTJKTWFWeENUdjRPdHgwCklBR2ZtaUlOS1p5LzZIYnpqVUJK
            L1dXblJYVlVaKzNKQkZ0dGFwYzk3eFEKLS0tIDlFUmVvVlE5c0VHRTVjY0MzYVla
            dFdJeGNES2pKRXpnL05LczlDbUFjZzgKTmzCwrE1d0BmxQRc5KC4oYdHBMY5BLB8
            +D+OVmHrZhDOw60mOWnOK/eUupne7z4aWU52O2yEQmiZ47/O1Xd/pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T19:10:52Z"
    mac: ENC[AES256_GCM,data:/r6gmlEJytibNJh3iWWiBZsXJopXZKKor2NWehI66B017PHW5MwCNG3pVgYAhC4Mu9nxk1Rh0BzidhlOOVM5UvbeI0/6uK5t2mHZcKd2BKkQRKX4XcIG4zBLP/DULrR8n9ptSdBzzVz4Lu3u3cKUjIvC+3AMbyw5dPnaeaSLTFw=,iv:UEDD9NwS8kHSgGK76MIQxhirJBmDTnS+PdfWg15kO4o=,tag:yaRePWbS/ImxqPrqmLmqYw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
