apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2NooFPnRo+8cqdJZzggE3YUI2kMbmgGTlrDdL8cZ+rgwjtKdMWZw/VX97UoY0CMW/UfMjYrjHLJWDanV6kb5H5wjIAHdv78EpyU/ULF2OGJHpn/tDxwG9GOsGEALywb782oUm1g6CdGrCrZ1A0k6EprBLrXt1sscN3yzNPfJisUKbTb8YTbc42XGGjIKhJWRN7DvnQeqQjus8ojsrRRmWBNJoizfffYpKDObXHXOZ6v9ZCaDNdKVg388z1GuZvBEC8E71s0YPDZ12A74WmSOZtvz6M7LqLKwR+vOgAam7A/YIOXcdaKcJ6PWwLPtx3J5N9clGHXBc5VKuxbL5je+NJ+C/gCaV8SRT8XS9AND97DbcLryRXAamHsmkXEjq1l5,iv:6ob2d5FnbJZxD2auvk2PWXtLg3lID3c5JIbyEXseNMI=,tag:3GUJ+DpNtAIVubbVao2rsA==,type:str]
    identity.pub: ENC[AES256_GCM,data:llgXHkVlSZx5cKeHYFdIKI46qrVlwnrsNKYb5dKmY3sBeQHXCSXfHR7bBoMcgtcHix4zoDsrpilZoJoeRg/ZCKRcGgwFCGLIp9tHh0gd+ZTvfgc8hRJITwLWYlO/Vnt1ftHurqjNJTDyHg4Ag4CuEGfYuLAjCsmJr6ulKFiwXL4eQX6WuLO1NS9XH2N1je6G/i/mJEUeGP3Z4aFJ0yyD8N/Zp55Tlo0SvY3yPdx0E/P3vW6E8XhPFzjB+YaUdmf5r98D8yl0lJ94yjqKPw==,iv:BeldIlJEHyPdoPsrb7Io3ulHER2s8SrNbIkSj1e56fU=,tag:pA4AegYN0YOcfmO/DQ8pXA==,type:str]
    known_hosts: ENC[AES256_GCM,data:e2SjEjEd5FT3HSgIlhZArYE6Wg0S/7+hwj9dB1kjI8n5yJhr6GPAscfHVnSFJaN6ZJK4Kijflw4n44QpcKvbpZSbddXfY3XXC3CJyUZ3V2FSHuLA/r/oC+YlPbISy/0z38dN/mZP9T/NpAgcHC4zkWB/PYpunQyDjNX0SKi3DsES3AIKtxOnScf1hCb5RovqV1OQ6bbQaJUq5bjg+EEw6cD84mKXzEA3KPgX,iv:VKsx0Wh7dXPgjg3KLhqBSCIsovk6MyUz+/L/M3mpTv4=,tag:YU9xnaelijqeqPdJrwOwbA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS0h2c3RNMTNxR1FJNk9J
            SmI5Zm10cXVlVzIwSnJ1MjJiZThSTzBxK1dnCmZxTkFHT3ZQb1FLNWxSQ2k3dlcr
            N3I1dkdKK3lVUjMxVHJVeGt6SU5yRUEKLS0tIFZ5djYreFdORlpscHRaOUZsbUdB
            azE3TWQ3d1djTk1rM1hzc0ZNd0ozajgK5CSaahbDmUJtsbEFrYVWIS4poZV1fIBQ
            QiLj0tHgEeSGntvz37LBGBwp6N2J/L6UCwc23nVvyjIo+v6hsWsW0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T21:35:08Z"
    mac: ENC[AES256_GCM,data:E/CuBjLw+UxN9iFfwrPhoRpT/OnLjQbdCB8j7jMq+HoubRvt/i3hOQghRwLAeQnZs7sk7KExdYVRCWms5nXFJUk/BXZDruxo5bkHukvPUR3+vU0vb2L5SRRDBQ6NgyLf+FgYwnPPhIroYEnLPW28AIErZL1mVz6u1m8Y5fe44qQ=,iv:XYkXuUmwRG/hhbdZnXgh4k5EmmrTzd8jB4yaRdaFjKk=,tag:HRd/hevYNzBWmSFVWV+OMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
