apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PsFwb7Vw+4rtnnEpP8oSe7wwxgDBMA2OjZdnGWi3jfFJVpVSjUWYtuXJ4wqUNkVz1Bw/W2pZwrV4XiFPfs8hetIKyjVJyC3y5PmCHPXA0MrT96+gRRBQ9nAmbcqpYJgThzoOTpEW5cXb3A3j85v1a8QqZqzMeUVV2BY6Un3Aq1nHSyuYnlxGuDU8ppvI7vJJfPbg83VgGEhFIkz6Evsc0lJuLt/3nruMw64TseKW6sZHAC/p85cNVzbXz4wtCWUnYDpSHxi/Ge/QhuXS1b/zU3d7Lj5amsacP+l7L/yuE1HAWy6XX59aACOBPp7AG9mN1JVBVv2J0ik+v7MBV4viIhO6FKtwzTB5JjeLSWRwqDkW222BhROeKe22jWxzODwG,iv:AeYU/BlmWQz2DvcLJzVt7hrt/Ts8f/ZXn9rtZHXVmSo=,tag:lDLFXzk4VHaF/sffH0loZA==,type:str]
    identity.pub: ENC[AES256_GCM,data:O+ZZOr91brkufFUPkvK6tYEYUsft2K0pEpiVhDWIMdg650G2CP21N0aAeuYe4ZReqUW7GF5lEtFfXsjfTsicmyqu3DwlA8sqzOh+pq5UjYNNgZW0ih/qTGnOMFZcnHZbaTa3tXzXchvYKCALCUlENwV1bVzAXBbcB8YitgDo+6XGARhlQVBURLjx3d5naesBKJn2l4jLoH8+NR1lWKcfi+BXlIuvqWBzFJ3O98ravWTbQXfSSccsHS8cfd2r1zKtHfVzpu45ZsLJXYZtUQ==,iv:L4myXA6W7H24J6nvoQ5GNbNOoE5eDEbJeQU7BOZEoY8=,tag:XI21zwJ/uAnvjEh/mBjIGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:4fNjtqhuTrjNJtdIxBQmXJOkPYQIJNkcIqBDKyTms/nOzmMRIfa78QYnwvGf+CrviBzkveULKM2VcR+QiqUxozQJGxRwVie9JxPBp6JjSTLZehgRz1BXmBYE4h8PucwisMBgF+TqoN4CfrFGupShgYLTHo+XP8GRFk8/kHRpJG/dyLlCewfKpf0xE37hQ9Mfq7LUlKxv0kTZc+WD3ry3lR179XkurGlekOy9,iv:k6xLlx/+hnuXvADLfKVaV/zZ4BZhGWI6olFYyLuiab8=,tag:Rnt94j5IdntpXtmKf4IeaA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdWh2aFROd21pNjdQSHU5
            VjVxeWhHVThWRXZEdjB0eDZMMTNIUEljbjBjCk02b3M0WVA5Tlc3anNkQnBIVVFt
            V0dsSUhZbWtrUjY3bUF6WG4wcFI2SU0KLS0tIDRtR0w3RGZYangwTnB0Y000Tml1
            eHpPNm13VGw5cWJDYjhHQW1rZXRWc3cKW7eJ3jGnGPJWOEm213+KGhyR/3y83k27
            lfpnHiK3tWrUOqTOwW6FzuzRlj39CgQZMdEpTQwTBae2uG3+M+UxIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T00:22:20Z"
    mac: ENC[AES256_GCM,data:wdjCLFgcWjSjK08yzFq8jPd1ATFS4ZXmr8+Ihv8SMij3opwQI6g5qbMzcvaTjgEj+w3pBxRrC3sT+4FHERjPp6VhpSUtu1gyzVcocttJB8Q/fFwDvh1tKWO6H1ydzlorcHOZLSB01eAUYzWBLxeCW9Kj+aUSDwo84eP5yvqy9c4=,iv:LE8WSJB2pupHhFcDsDENyCbawGVrIf1cVhZc6SjM9Js=,tag:fXSnVAonF8IPJFK0TWCfWQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
