apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rwWPawSfpwPpNkr7IB5EqUWeKOYqm9iZtIh6uBz7daZCUB4At0QS40W8L/SbKx1bM5w1FUsgGyN8hC17MOQ4O6otL1qEHKU5UZSOIRpLWar39I3Q7QKdJKuNf6l7ADi24beW9wpVJnH5M0Us5aVy20li7lfF+Gre2QnPGptDFyrTygMOfaJQMoqRTsTGK68UWGVN3NRYOCQWjvDj6/2cspLdF6/tMX38+nUg0YwME9GOKaXN2jvxl+TSkeeG6aVjXwE5nB9GxL1OxrTIgVLfan/GZMkeGVftlXpeDwsaHsi6GP+HM2bpUyBDu1rKe9DBCw04UAsTwdmKZ8rwT0JNIk+2O5Pr5XdKwZVjNTIHu6lCXiQX1btkRb6D2jxwq8Ah,iv:cF6bZ3GFee1A7TvSW1EKvT6/4sJpETSCo9HT6KkUix8=,tag:aZJO7Vpgr1HH8Hw6dnrtTQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:FPB7cw5Dn1scStaRP1r5LMqsl/7WRzCZ4Ob50skZlFBHjH9UbwwBqJuHm1gOfXFn4RkjWI+U4Zsqb47XILDqh8rUOWpUFvmV6/BsR23NZL8SRwOgRDA/EhT0UTJvhyDYX4Bgp0YnE3pqB92/9Y/CDSgebQLfuyA/R3K9/7QPZC+BxKKOTxSAwuw6hjbm2zxSxXgwLhhVddW/jerJZ8lfih8LRm2EMR6DvabrU7QDAXnzg2ZzLMyvnRs7MQITqR6nDh8a4ORVh4nqsREDpQ==,iv:OG1OggcO96+cLWnUt8IWRrPkxYVx7OXBcDY51zhoYpA=,tag:zlpVdGryHuffz4ayNhkNUw==,type:str]
    known_hosts: ENC[AES256_GCM,data:K5WDlm7qNKXReNQNmHPof6ztlMJ9PjgJkzhKoe9MpLaCKMji03I2RfdPIfITSGANeKrV5ZInSc17dtr+pZGrzRGMkgJMXg6lGZJAUKAo/F+mNKU1YHLQvhUmSZ262nUmX4XVAQ7IRS+BoCwuZs5it7BgCE4ZxoDz9hhree6qhQN+xpjLrgAiu612Q14r/IzV9vfPczSdCbILfpPtarlekpWG3Z/5zTXF4g7p,iv:Teo9iDT/vHJFDbpweq+YZkjMEp7YacP9b/DULue5gQc=,tag:FNOTK4slQEajF8MV+KnzXA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYXpiLytvWFVYbzRYUDFh
            VEdra3RKNmpqQnRXSGloL25kVVdhdlg3clFFCktrQ1VtQ2hnbmZ0dkdWK3BETTkv
            NmtDK3YvbXJPb2ZvcVNTY3pqWjB4ZDQKLS0tIFFlcG9JVDRyZCtTL1BySzl4Rkdy
            bmFyV0FaR1pDNE4rZ2MzOTVaNGZFeW8KN3mEiXgOaAXZ4t4BUoK2mkfUZ/C5nHfr
            9p0goT8xDbdSBjw1hwjJLcQwOJMS5hDssQQTmg5voMfDXkzi3LI6FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:04:55Z"
    mac: ENC[AES256_GCM,data:YEH3sDNMnGpCOizXTX5vEySyImRWd6gm70MN22a459rh9GyXpThgQUY2w6B/Mb8l9HWH2nmPLItd08jwd0/q+lcluv/yE9YxAbUXgJptwCYu2A/lTjF5+EUR1aPPkHg5zPNNQ+rc/NCf6VoBJBPSOD8FLtrFabY+cRyC1apm++8=,iv:WbHSUWCOs8NB5L9kpMagKC4HXMO+5mPAJ29knjZXFTI=,tag:/DnW/88sLr8k5I9Jso/QgQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
