apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:m2nn1lLpI9h1HoH9gdLyHzURTulSz6Bw4hBjkfeosBdlSEnhK4vX534qSQ2fAHdGTgk+w0ycrNZNS7ZqFdQmvpeSjsl6Iu743vf25eVHVqN/P/Moc2HQnCcjezoPKxv5eABZW+vu4TnoB5TYaQgFcsYFKPr4+wYXLn/xtCaPzf6CXlMJO2QXEPe8NUvM6kSSqPPV2c4pnQ13CaXoOCeN501nlEXMZRYhCZ/WEbgBg6eFoBoMH6XaJ+Eu9Ub2fZBOjeuxNPQNPaDHv/8sWoxTPOgEP144HMAG3ZImS/8UzqqRNgBet/2PKEaMLdjVWwRY6HM4yUz7RWZo6UdmU+I6CxigE2cJF6UU/U2wJ7fJPZGYVPdhcqVBOGGsUsWUTL12,iv:Ak+VUvgb7YLB5fl31tEvMVSJgetdewWz+QgHtdKSpD0=,tag:CfakE7mI+lgi+kftAJfgSA==,type:str]
    identity.pub: ENC[AES256_GCM,data:owm2yylLlwA/YtALiSNITYWA+TcNmLd3JQpQDK+2iQbcgbFXzR9T+yLZFtFbs5ms0VOviqgzEavqECWfznk3R0GfNjagN+ikIGrrKk+wUXbOhriugj9vgc6JFdujTEif+qVcf47sjqVsaeQjdDBTbO2RZyd0mBKR4072kl5SuP3VY1X2BMaZow+r0uFiSOMOLt9XpXlfX0GztGYWhmTwErkORpWD8ufenpFIM3b39B+xLZ1yCwNEwmk2FDTv0kuC/djlf9sh3skEE7m15Q==,iv:pjciPZw7cyAnjhNvXpo8JRqQBBD++ywsfLoWdQU3JYk=,tag:Lnlgw7EVXvR7/fbbJGIbKw==,type:str]
    known_hosts: ENC[AES256_GCM,data:gn1SK/9lcehgxnDdLfrnlBEa52wK7yGNGU+fe2dEQJstoMbuyMrsqLVx4aBROCKMq/eSwnxXwHri2Q5JGnW6wBikxiDAOIQsN757b9MEHL/7R54iDWa6laoVBhAX3HNbbG+CrOk7V8fCV/XvO/cFwafa+nI7zFAH1p1EZ92Tw41fZVzJTNj9Uv2RfLpMMgKOS+dEk8TTJkinJjlBFOM9h96FlZ9xILinr2rD,iv:O4Bdnvby5TvndhMxYp6OQJ6qdgrSs7p8xyHX1PvJ270=,tag:sd5yoRUumoMOGh6+RwpJBQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwc3FyaXJCbVEwRDVOUXoz
            UlhMMXRPWmI4M0N4NWdsaEhoR2I2UExYTkNzCllpbE94bURVWmlScGo5Z0xEWTFm
            c0s1b0lJNEQwWXdsaXZpZDl5S20yUTgKLS0tIGMzTVVLZXZJOTRDMnd5c25hOHlL
            T3VUbmJTNU1vQmpadnZqalhXN2Iwd2MK5Lco2sL5EHCXRtm6rJKhVMouPCr53Vak
            pIYD+BiDgjwp2XNL4XeBHBLXi/xGY9J/joGnBqEgMvIVg1XckzkrlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T00:29:16Z"
    mac: ENC[AES256_GCM,data:s4WSxwKVH9v/tQIMDTm3o75r16ny0qVjA4qz3qTgcXLjjdOg9vu7BbMlf6sPkQnP4a/frKwuuFUrYmDzZdBdVg15tSdw2sx1Xxl+yAOXvf3FrfLykOAA4yWESBOt9g08pHtklMEIQWgbWXWDTx9vXl0RANb8jNv4NnLCZkEtZcE=,iv:ld5tktT+Eqbg0ANsI8dNPy8Nn3dtW6S/EqB2UHUmryE=,tag:tQi5gjZpZcyrenjE1/wxPg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
