apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7Ku/CiAOfDwrPuauGqpHEn1Z9qKYNyMLHmjRCPbrjvc2/1Z1x+iSc23wiep1blQT8CcK1jX1GH9Z8GcM7F0DD5HB2rw97AdLVKvKjWotEfchYo2siJ/PwoskDnFTGymbnfP68o1aF2pY/XdmNAwh5nT7qXDlS2jae9pPo+HZa2FhWe9s1Qpcd4rNEoAQYBJBSFory+zfV4zOLht8d4DkiOxxHOZEPo4MA26wJyXorscN0EJ4Ygw9rfMpDGn/xO8/bxxE2q7/Gd7bHQbBc3yvO81Vcw5zcoZ9FXVHSwtpvEzugPXniUg1t7j2D+jhpU0TlwGboya5S0Bk7pAn08bCJfCsWTpsM/dQgkOyZXbWlmqJ0Mvx4vexB9QYwQTcOQm1,iv:lvYcJ1Wx3a2AscEFVA9d5Qoua1z0+VB3jikfxg9YNxw=,tag:9L3K8ow3hjlRi4l5XOwNPw==,type:str]
    identity.pub: ENC[AES256_GCM,data:aho2aZIYMJcVRKElOtnY1Kbdq3YyQQo4PkC7SAu+dtOXp5LzlZxddocbCEdoEO2glaV/e0/aZWBCDERsk3vPht0RQ9kQZZF+ajAlQtaZcqYbDpUGt4jYiiBmJ9JKGvxEzJLJljU9tAC6Aa+LQIS/R+9idDI6JTIS6QvTqz8/Nvzkbm8R3MnSHDqSyoOeT0ijPcTdQFaGdQnfJoKaCUIv5/GkcCN9CSrz2N/PP8SyhwdNduC7SdxLFO7JTIzauPOw8mjIwgSK1t6d8/qbnQ==,iv:r/jwh200dv0nsKkGUrZ1Zk92/zlMXuiil5ok0CcrpdM=,tag:enCwls530+t4ayH4t98Sng==,type:str]
    known_hosts: ENC[AES256_GCM,data:wU6zM22amURP8Yi3JJLFlU7J0rXLxTS3X70DoEm1UmNLmj3cCw53bYURQC1qyj/gsa9wMsyE9514y62JiQ+hkQQMKKGm6PqlCAtO2Q6M+O3mq2Xm/ziqbrJzZwfc/07wsh1BeiKpR4dm21IA0iekU91io4HtZzqxmSMsqQQKxjQeFs7biK1+dqebd3pi1NRjpbzUKjyAWzMzoEm4cTOwickkndpvSx+XjVSW,iv:WA0re7I6qbGH3S1rAuMTCdQ/k1kwx38bjzvqVxtAxYE=,tag:+7qBOOKnILwMzZhSEkB/GQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUHNCbmpZa1pLaCtOVlBC
            bkZHcE1JN3F3NlNscFQrcjZYTlA4akF6NWlVCkRJU0ZZNnZNQnBlTEwwVzBScW5U
            WlpzN3RhWm9YblErTHZkVUxYKzV6Y2sKLS0tIFl4bm5KclRDc3ZYTm9ucmZzWkFp
            UzNxb2NoN3loNCsyekg3cGZMcE9HODAKlFHC8GjshxhN0+HgA/6zLrry65BOvPIL
            hNwyZcHV1AqW5URK72JOJB3XfFlZ+aYTf00H+rDqthLM57xYlGIZsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T15:11:34Z"
    mac: ENC[AES256_GCM,data:ZPC41vOY2g/DzBw+9tVzhNKupg9u66CSdXyc+M7W8nkurEmPbkpEMN6ZLAf4LMNUlIRkJ7MA+h85erUzxPGYEuSoQnNcqRQlHZlvgboFIaPxg/WEEABNc27+HZYYkeQ81nIUBObGMNSZjb9l5Kj3JAM/3Civt5NCCEqW0H6WPgw=,iv:bWqxhKjIRktmwtYAvP/qhCg1Kbc1rraR2RqOddE5aIo=,tag:GqNT4VqJdGUEyGRkuivL9Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
