apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: steam-headless-controlplane
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/my-apps/gaming/steam-headless-controlplane/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

