apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: worker-node-taint
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/worker-node-taint/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

