apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wow-bots-mysql
  namespace: gaming
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 15.36.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    image:
      repository: mysql
      pullPolicy: IfNotPresent
      tag: 8.0-debian@sha256:1ae7ba07e714856c61aa0d559a8f1a788eb8f25bd0b5b71738a1bdd6798bc022

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MYSQL_DATABASE: acore_auth
                MYSQL_USER: ${WOW_DB_USER}
                MYSQL_ROOT_PASSWORD: ${WOW_DB_ROOT_PASS}
                MYSQL_PASSWORD: ${WOW_DB_PASS}
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            protocol: tcp
            port: 3306
            targetPort: 3306

    persistence:
      data:
        enabled: true
        type: nfs
        mountPath: /var/lib/mysql
        path: ${NFS_GAME_SERVERS}/azerothcore/wow-bots-mysql
        server: ${NAS_IP}