apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./system/node-config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster
